### ISSUE TITLE
[BUG] sqlite3.DatabaseError: database disk image is malformed

### ISSUE THREAD

**Issue by PChuckran** [merenlab/anvio#1796] opened 2021-09-10 21:46 UTC
## Short description of the problem
Hi All,

Trying to import KEGG annotations to a contigs db and keep getting met with the following error. I've tried building the database again, but I keep running into the same problem.

## anvi'o version

```
Anvi'o .......................................: hope (v7)

Profile database .............................: 35
Contigs database .............................: 20
Pan database .................................: 14
Genome data storage ..........................: 7
Auxiliary data storage .......................: 2
Structure database ...........................: 2
Metabolic modules database ...................: 2
tRNA-seq database ............................: 1
```

## System info

Linux, installed from conda

## Detailed description of the issue

```
                         source  ... e_value
gene_callers_id                  ...
2588             KeggGhostKoala  ...       0
20762            KeggGhostKoala  ...       0
23169            KeggGhostKoala  ...       0
23626            KeggGhostKoala  ...       0
24592            KeggGhostKoala  ...       0

[5 rows x 4 columns]
Traceback (most recent call last):
  File "/scratch/pfc25/conda/envs/anvio-7/bin/anvi-import-functions", line 101, in <module>
    main(args)
  File "/scratch/pfc25/conda/envs/anvio-7/bin/anvi-import-functions", line 75, in main
    gene_function_calls_table.create(functions_dict, drop_previous_annotations_first = drop_previous_annotations)
  File "/scratch/pfc25/conda/envs/anvio-7/lib/python3.6/site-packages/anvio/tables/genefunctions.py", line 114, in create
    self.add_new_sources_to_functional_sources(gene_function_sources, database, drop_previous_annotations_first=drop_previous_annotations_first)
  File "/scratch/pfc25/conda/envs/anvio-7/lib/python3.6/site-packages/anvio/tables/genefunctions.py", line 69, in add_new_sources_to_functional_sources
    database.set_meta_value('gene_function_sources', ','.join(list(gene_function_sources)))
  File "/scratch/pfc25/conda/envs/anvio-7/lib/python3.6/site-packages/anvio/db.py", line 119, in inner
    return func(self, *args, **kwargs)
  File "/scratch/pfc25/conda/envs/anvio-7/lib/python3.6/site-packages/anvio/db.py", line 184, in set_meta_value
    self.remove_meta_key_value_pair(key)
  File "/scratch/pfc25/conda/envs/anvio-7/lib/python3.6/site-packages/anvio/db.py", line 119, in inner
    return func(self, *args, **kwargs)
  File "/scratch/pfc25/conda/envs/anvio-7/lib/python3.6/site-packages/anvio/db.py", line 191, in remove_meta_key_value_pair
    self._exec('''DELETE FROM self WHERE key="%s"''' % key)
  File "/scratch/pfc25/conda/envs/anvio-7/lib/python3.6/site-packages/anvio/db.py", line 300, in _exec
    ret_val = self.cursor.execute(sql_query)
sqlite3.DatabaseError: database disk image is malformed
srun: error: cn61: task 0: Exited with exit code 1
```

Happens even when I tried to rebuild the contigs database. I looked over the original contigs fasta and didn't see any glaring issues at the head or tail. 
Thank you in advance,
-Pete

**Comment by meren** [comment] 2021-09-10 22:07
Hey Pete,

Sorry. This looks frustrating. That said, looking at where this error coming from in the code, and reading more online about [this particular error](https://sqliteviewer.com/blog/database-disk-image-malformed/), I can't imagine how it could be related to anvi'o. But here is an idea:

If you re-create your contigs database, and send to me privately (a.murat.eren at gmail),

* the original db (without running `anvi-import-functions`),
* the file you're trying to import,
* the command line you are running

I can try to see if I can reproduce it.


Best wishes,

**Comment by PChuckran** [comment] 2021-09-15 15:14
Thanks Meren,
The contigs database was too large to email (1.8 GB), so I tried to subset the contigs and rebuild the database to send to you. I was actually able to import the kegg functions to the smaller contigs database, which makes me wonder if the initial contigs file was too large. Based on the link you provided, it looks like this could be plausible? Still new to anvi'o so I am not sure if a 1.8G contigs database is reasonable or not. Thanks again for your reply.
Best,
Pete

**Comment by meren** [comment] 2021-09-15 16:43
This is concerning indeed. We often work with contigs databases that are over 50 Gb. So I don't think the size is an issue in general, but that is something I must test.

You should be able upload the DB to Dropbox and send me a Download link? :)

**Comment by meren** [comment] 2021-09-16 00:07
Hi @PChuckran, thank you very much for sending your files. I have done some tests, and I was unable to reproduce your error :/

Here is how it went. After downloading your files, I got a copy of the GhostKoala to anvi'o repo and run it on the `user_ko.txt`:

``` bash
git clone https://github.com/edgraham/GhostKoalaParser.git

cd GhostKoalaParser/

./KEGG-to-anvio --KeggDB samples/KO_Orthology_ko00001.txt -i ../user_ko.txt -o KeggAnnotations-AnviImportable.txt

mv KeggAnnotations-AnviImportable.txt ../

cd ..
```

Before the import, I checked the database to make sure there are no functions in it:

```bash
anvi-db-info contigs.db

DB Info (no touch)
===============================================
Database Path ................................: contigs.db
description ..................................: [Not found, but it's OK]
db_type ......................................: contigs (variant: None)
version ......................................: 20


DB Info (no touch also)
===============================================
project_name .................................: C0_co_2_3
contigs_db_hash ..............................: hash73c90a19
split_length .................................: 20000
kmer_size ....................................: 4
num_contigs ..................................: 434094
total_length .................................: 765244086
num_splits ...................................: 434364
gene_level_taxonomy_source ...................: None
gene_function_sources ........................: None
genes_are_called .............................: 1
external_gene_calls ..........................: 0
external_gene_amino_acid_seqs ................: 0
skip_predict_frame ...........................: 0
splits_consider_gene_calls ...................: 1
scg_taxonomy_was_run .........................: 0
scg_taxonomy_database_version ................: None
trna_taxonomy_was_run ........................: 0
trna_taxonomy_database_version ...............: None
creation_date ................................: 1631551138.17007

* Please remember that it is never a good idea to change these values. But in some
cases it may be absolutely necessary to update something here, and a programmer
may ask you to run this program and do it. But even then, you should be
extremely careful.


AVAILABLE GENE CALLERS
===============================================
* 'prodigal' (1,013,895 gene calls)


AVAILABLE FUNCTIONAL ANNOTATION SOURCES
===============================================
* No functional annotations found in this contigs database :/


AVAILABLE HMM SOURCES
===============================================
* This contigs db does not have HMMs :/
```

Then I imported functions:

``` bash
anvi-import-functions -c contigs.db -i KeggAnnotations-AnviImportable.txt

Gene functions ...............................: 438,575 function calls from 1 source (KeggGhostKoala) for 438,575 unique gene calls have been added to the contigs database.
```

Everything seemed to went well. I then run `anvi-db-info` again, and could see the functions in it:

``` bash
anvi-db-info contigs.db

DB Info (no touch)
===============================================
Database Path ................................: contigs.db
description ..................................: [Not found, but it's OK]
db_type ......................................: contigs (variant: None)
version ......................................: 20


DB Info (no touch also)
===============================================
project_name .................................: C0_co_2_3
contigs_db_hash ..............................: hash73c90a19
split_length .................................: 20000
kmer_size ....................................: 4
num_contigs ..................................: 434094
total_length .................................: 765244086
num_splits ...................................: 434364
gene_level_taxonomy_source ...................: None
genes_are_called .............................: 1
external_gene_calls ..........................: 0
external_gene_amino_acid_seqs ................: 0
skip_predict_frame ...........................: 0
splits_consider_gene_calls ...................: 1
scg_taxonomy_was_run .........................: 0
scg_taxonomy_database_version ................: None
trna_taxonomy_was_run ........................: 0
trna_taxonomy_database_version ...............: None
creation_date ................................: 1631551138.17007
gene_function_sources ........................: KeggGhostKoala

* Please remember that it is never a good idea to change these values. But in some
cases it may be absolutely necessary to update something here, and a programmer
may ask you to run this program and do it. But even then, you should be
extremely careful.


AVAILABLE GENE CALLERS
===============================================
* 'prodigal' (1,013,895 gene calls)


AVAILABLE FUNCTIONAL ANNOTATION SOURCES
===============================================
* KeggGhostKoala (438,575 annotations)


AVAILABLE HMM SOURCES
===============================================
* This contigs db does not have HMMs :/
```

I can even search for some functions as you can see:

``` bash
anvi-search-functions -c contigs.db --search-term reductase --verbose
Searching in Contigs Database ................: contigs.db
Contigs DB ...................................: Initialized: contigs.db (v. 20)
Search terms .................................: 1 found
Matches ......................................: 15401 unique gene calls contained the search term "reductase"

Matching names for 'reductase' (up to 25)
===============================================
 CYTB, petB; ubiquinol-cytochrome c reductase cytochrome b subunit
 norC; nitric oxide reductase subunit C
 msrC; L-methionine (R)-S-oxide reductase [EC:1.8.4.14]
 hdrC; heterodisulfide reductase subunit C [EC:1.8.98.1]
 gyaR; glyoxylate reductase [EC:1.1.1.26]
 ssuE; FMN reductase [EC:1.5.1.38]
 torC; trimethylamine-N-oxide reductase (cytochrome c), cytochrome c-type subunit TorC
 prmB; propane monooxygenase reductase component [EC:1.18.1.-]
 ispH, lytB; 4-hydroxy-3-methylbut-2-en-1-yl diphosphate reductase [EC:1.17.7.4]
 E1.3.1.32; maleylacetate reductase [EC:1.3.1.32]
 chlN; light-independent protochlorophyllide reductase subunit N [EC:1.3.7.7]
 ndhD; NAD(P)H-quinone oxidoreductase subunit 4 [EC:1.6.5.3]
 frdC; fumarate reductase subunit C
 ydfG; 3-hydroxy acid dehydrogenase / malonic semialdehyde reductase [EC:1.1.1.381 1.1.1.-]
 frdD; fumarate reductase subunit D
 narI, narV; nitrate reductase gamma subunit [EC:1.7.5.1 1.7.99.-]
 MQCRC, qcrC, bfcC, petD; menaquinol-cytochrome c reductase cytochrome b/c subunit
 xdhD; putative selenate reductase molybdopterin-binding subunit
 rutF; flavin reductase [EC:1.5.1.-]
 PECR; peroxisomal trans-2-enoyl-CoA reductase [EC:1.3.1.38]
 sdhB, frdB; succinate dehydrogenase / fumarate reductase, iron-sulfur subunit [EC:1.3.5.1 1.3.5.4]
 proC; pyrroline-5-carboxylate reductase [EC:1.5.1.2]
 padD; phenylacetyl-CoA:acceptor oxidoreductase 26-kDa subunit
 ndhF; NAD(P)H-quinone oxidoreductase subunit 5 [EC:1.6.5.3]
 uxaB; tagaturonate reductase [EC:1.1.1.58]

Items additional data compatible output ......: search_results.txt
```

I'm afraid this problem is related to your system, but I have no idea what to suggest or how to solve it :(

I'm closing the issue for now, but please feel free to open it.

**Closed by meren** 2021-09-16 00:07 UTC

**Comment by PChuckran** [comment] 2021-09-22 14:49
In case anyone runs into the same problem:
I checked with our hpc system admin and they weren't 100% sure what was going on either, but thought that the job might be running out of time or memory and causing it to become malformed. So I added more memory to the job request (we use Slurm) and that worked. It was way more memory than what the job ended up using, but it's only for 1 step and I'm not going to argue with success.

**Comment by meren** [comment] 2021-09-22 14:59
This is brilliant :) Thank you very much for the follow up, @PChuckran!

> I'm not going to argue with success.

Given so many things we have to struggle through, I think this is a very wise attitude. I hope the rest of your work with anvi'o goes smoothly.

Best wishes,
