### ISSUE TITLE
installation problems

### ISSUE THREAD

**Issue by 17863952296** [merenlab/anvio#2118] opened 2023-09-19 14:11 UTC
when I run anvi-self-test --suite mini, I can make success it. but I don't run the command: anvi-setup-cazymes
error :anvi-setup-cazymes The command was not found

**Comment by metehaansever** [comment] 2023-09-19 14:17
Hello @17863952296  you didn't respond to the questions in the issue template. which requires us to ask the same questions that were already in the issue template. I'll close this issue now. please feel free to start another one, fill out the template properly, and consider including a completely reproducible example in it (i.e., put all your relevant input files in a directory, gzip it, upload it somewhere, and send us a download link).

**Closed by metehaansever** 2023-09-19 14:17 UTC

**Comment by ivagljiva** [comment] 2023-09-19 14:57
Yes, you should definitely follow the issue template. :) 

But to save some time, I can already guess the problem, because this is a common mistake. `anvi-setup-cazymes` only belongs to the development version of anvi'o. Probably @17863952296 has installed v7.1. If they want to use this program, they need to install the development version: https://anvio.org/install/#5-follow-the-active-development-youre-a-wizard-arry
