### ISSUE TITLE
Error in NCBI genomes download workflow

### ISSUE THREAD

**Issue by meren** [merenlab/anvio#1184] opened 2019-07-04 15:42 UTC
This is [reported by Jake Callaghan on anvi'o Slack](https://anvio.slack.com/archives/C8SFMGYF3/p1562086377079400), I am just carrying it here:

```
(anvio5) Jakes-iMac:Contigs jakecallaghan$ anvi-self-test -v
Anvi'o version ...............................: margaret (v5.5)
Profile DB version ...........................: 31
Contigs DB version ...........................: 12
Pan DB version ...............................: 13
Genome data storage version ..................: 6
Auxiliary data storage version ...............: 2
Structure DB version .........................: 1
```

## The Error

This happens when Jake tries to run the contigs workflow on genomes from NCBI:

```
"Error in rule anvi_script_reformat_fasta_prefix_only:
   jobid: 522
   output: 01_FASTA/Nitrosopumilus_sp__AR_GCF_000328925_1/Nitrosopumilus_sp__AR_GCF_000328925_1-contigs-prefix-formatted-only.fa, 01_FASTA/Nitrosopumilus_sp__AR_GCF_000328925_1/Nitrosopumilus_sp__AR_GCF_000328925_1-reformat-report.txt
   log: 00_LOGS/Nitrosopumilus_sp__AR_GCF_000328925_1-anvi_script_reformat_fasta_prefix_only.log

RuleException:
CalledProcessError in line 112 of /anaconda3/envs/anvio5/lib/python3.6/site-packages/anvio/workflows/contigs/Snakefile:
Command ' set -euo pipefail;  anvi-script-reformat-fasta /Users/jakecallaghan/Google Drive/Geomicrobiology-Lab/Graduate_Students/Jake_Callaghan/AnvioStuff/TACK/TACK-NCBI-GENOMES/Nitrosopumilus_sp__AR_GCF_000328925_1-contigs.fa -o 01_FASTA/Nitrosopumilus_sp__AR_GCF_000328925_1/Nitrosopumilus_sp__AR_GCF_000328925_1-contigs-prefix-formatted-only.fa -r 01_FASTA/Nitrosopumilus_sp__AR_GCF_000328925_1/Nitrosopumilus_sp__AR_GCF_000328925_1-reformat-report.txt --prefix Nitrosopumilus_sp__AR_GCF_000328925_1   --simplify-names >> 00_LOGS/Nitrosopumilus_sp__AR_GCF_000328925_1-anvi_script_reformat_fasta_prefix_only.log 2>&1 ' returned non-zero exit status 2.
 File "/anaconda3/envs/anvio5/lib/python3.6/site-packages/anvio/workflows/contigs/Snakefile", line 112, in __rule_anvi_script_reformat_fasta_prefix_only
 File "/anaconda3/envs/anvio5/lib/python3.6/concurrent/futures/thread.py", line 56, in run"
```

## How to reproduce the error:

``` bash
# Commands to download refseq TACK genomes for contig database
python gimme_taxa.py 1783275 -o TACK-TaxIDs.txt --just-taxids

ncbi-genome-download -t TACK-TaxIDs.txt archaea -o TACK --metadata TACK-NCBI-METADATA.txt

anvi-script-process-genbank-metadata -m TACK-NCBI-METADATA.txt -o TACK-NCBI-GENOMES --output-fasta-txt TACK-fasta.txt --exclude-gene-calls-from-fasta-txt

# Run the workflow. This is where the issue is
anvi-run-workflow -w contigs -c config-contigs-TACK.json
```

Here is Jake's JSON file is set up- the simplest version:

```
{
    "fasta_txt": "TACK-fasta.txt"
}
```

**Comment by ShaiberAlon** [comment] 2019-07-04 23:05
I repeated the steps described above, and I get no error (I used anvio 5.5, same as Jake.)

This log file (that is mentioned in the outline above) Could include a hint of what's going on, if Jake has it:

```
00_LOGS/Nitrosopumilus_sp__AR_GCF_000328925_1-anvi_script_reformat_fasta_prefix_only.log
```

**Comment by ShaiberAlon** [comment] 2019-07-04 23:10
I'm closing this for now since I can't reproduce it.

**Closed** 2019-07-04 23:09 UTC
Labels: invalid, snakemake workflows
