### ISSUE TITLE
DIAMOND issue with anvi'o v5 and anvi-run-ncbi-cogs

### ISSUE THREAD

**Issue by JBuongio** [merenlab/anvio#894] opened 2018-06-27 19:33 UTC
Hi Meren, 
I can't catch a break! I am getting an error about Diamond when running 'anvi-run-ncbi-cogs'. This issue is very similar to a previous one (#767), however, I am unable to solve it with a reinstall of Diamond (v. 9.18) and a re-run of 'anvi-setup-ncbi-cogs'.

```
(anvio-5) $ anvi-self-test --version
Anvi'o version ...............................: margaret (v5)
Profile DB version ...........................: 29
Contigs DB version ...........................: 12
Pan DB version ...............................: 12
Genome data storage version ..................: 6
Auxiliary data storage version ...............: 2
Structure DB version .........................: 1
```

```
(anvio-5) $ anvi-setup-ncbi-cogs --reset -T 16
COG data directory ...........................: /home/barbara-lloydlab/virtual-envs/anvio-5/lib/python3.5/site-packages/anvio/data/misc/COG
COG data source ..............................: The anvi'o default.
COG data dir .................................: /home/barbara-lloydlab/virtual-envs/anvio-5/lib/python3.5/site-packages/anvio/data/misc/COG

WARNING
===============================================
This program will remove everything in the COG data directory, then download and
reformat everything from scratch.

Press ENTER to continue, or press CTRL + C to cancel...

Downloaded succesfully .......................: /home/barbara-lloydlab/virtual-envs/anvio-5/lib/python3.5/site-packages/anvio/data/misc/COG/RAW_DATA_FROM_NCBI/cognames2003-2014.tab
Downloaded succesfully .......................: /home/barbara-lloydlab/virtual-envs/anvio-5/lib/python3.5/site-packages/anvio/data/misc/COG/RAW_DATA_FROM_NCBI/fun2003-2014.tab
Downloaded succesfully .......................: /home/barbara-lloydlab/virtual-envs/anvio-5/lib/python3.5/site-packages/anvio/data/misc/COG/RAW_DATA_FROM_NCBI/prot2003-2014.fa.gz
Downloaded succesfully .......................: /home/barbara-lloydlab/virtual-envs/anvio-5/lib/python3.5/site-packages/anvio/data/misc/COG/RAW_DATA_FROM_NCBI/cog2003-2014.csv
Diamond log ..................................: /home/barbara-lloydlab/virtual-envs/anvio-5/lib/python3.5/site-packages/anvio/data/misc/COG/DB_DIAMOND/log.txt
Diamond search db ............................: /tmp/tmp6r0bs8yu.dmnd           
BLAST log ....................................: /home/barbara-lloydlab/virtual-envs/anvio-5/lib/python3.5/site-packages/anvio/data/misc/COG/DB_BLAST/log.txt
BLAST search db ..............................: /tmp/tmp6r0bs8yu                
(anvio-5) barbara-lloydlab@lloydbarbara:~/klds1515/SVA08.16_Metagenomes/071817KLmetagenome-45705703/Bins_from_Derep_Dastool/After_sortmeRNA/For_Anvio$ anvi-run-ncbi-cogs -c Concatenated_MAGs_simple_deflines062718.db --num-threads 16
COG data directory ...........................: /home/barbara-lloydlab/virtual-envs/anvio-5/lib/python3.5/site-packages/anvio/data/misc/COG
COG data source ..............................: The anvi'o default.
COG data directory ...........................: /home/barbara-lloydlab/virtual-envs/anvio-5/lib/python3.5/site-packages/anvio/data/misc/COG
Searching with ...............................: diamond
Directory to store temporary files ...........: /tmp/tmpfav9yru4
Directory will be removed after the run ......: True
                                                                                
WARNING
===============================================
8 entries in the sequences table had blank sequences :/ This is related to the
issue at https://github.com/merenlab/anvio/issues/565. If this is like mid-2018
and you still get this warning, please find an anvi'o developer and make them
feel embarrassed. If it is earlier than take this as a simple warning that some
gene calls in your downstream analyses may have no sequences, and that's OK.
This is a very minor issue due to on-the-fly addition of Ribosomal RNA gene
calls to the contigs database, and will likely will not affect anything major.
This warning will go away when anvi'o can seamlessly work with multiple gene
callers (which we are looking forward to implement in the future).

Sequences ....................................: 111492 sequences reported.
FASTA ........................................: /tmp/tmpfav9yru4/aa_sequences.fa
DIAMOND is set to be .........................: Fast
                                                                                

Config Error: Pfft. Something probably went wrong with Diamond's 'blastp' since one of the
              expected output files are missing. Please check the log file here:          
              '/tmp/tmpfav9yru4/log.txt.
```

Contents of log file referred to: 

```
# DATE: 27 Jun 18 15:25:11
# CMD LINE: diamond blastp -q /tmp/tmpfav9yru4/aa_sequences.fa -d /home/barbara-lloydlab/virtual-envs/anvio-5/lib/python3.5/site-packages/anvio/data/misc/COG/DB_DIAMOND/COG -a /tmp/tmpfav9yru4/diamond-search-results -t /tmp -p 16 --max-target-seqs 1 --evalue 1e-05
diamond v0.9.18.119 | by Benjamin Buchfink <buchfink@gmail.com>
Licensed under the GNU AGPL <https://www.gnu.org/licenses/agpl.txt>
Check http://github.com/bbuchfink/diamond for updates.

#CPU threads: 16
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
#Target sequences to report alignments for: 1
Temporary directory: /tmp
Opening the database... No such file or directory
 [6.5e-05s]
Error: Error opening file /home/barbara-lloydlab/virtual-envs/anvio-5/lib/python3.5/site-packages/anvio/data/misc/COG/DB_DIAMOND/COG.dmnd
```

```
(anvio-5)$ diamond --version
diamond version 0.9.18
```

Should I install the latest release of Diamond?

**Comment by camillaln** [comment] 2018-06-28 15:53
Heia,  
I have gotten a problem with the COG database search after upgrading to Anvio5. I installed anvio 5 using brew install anvio (and then it told me to do brew upgrade … or something like that. I followed the orders :)

When doing  anvi-run-ncbi-cogs I first got a message that I needed to “re-run the COGs setup”. I did this, and now I get “Config Error: Pfft. Something probably went wrong with Diamond’s ‘blastp’ since one of the expected output files are missing. Please check the log file here: ’/var/folders/nf/crn9cwk14r9d_bklwmm8j7280000gn/T/tmpzbjtihi8/log.txt.
Log file: 
# DATE: 27 Jun 18 19:15:41
# CMD LINE: diamond blastp -q /var/folders/nf/crn9cwk14r9d_bklwmm8j7280000gn/T/tmpzbjtihi8/aa_sequences.fa -d /usr/local/Cellar/anvio/5/libexec/lib/python3.6/site-packages/anvio/data/misc/COG/DB_DIAMOND/COG -a /var/folders/nf/crn9cwk14r9d_bklwmm8j7280000gn/T/tmpzbjtihi8/diamond-search-results -t /var/folders/nf/crn9cwk14r9d_bklwmm8j7280000gn/T -p 1 --max-target-seqs 1 --evalue 1e-05
diamond v0.9.22.123 | by Benjamin Buchfink <buchfink@gmail.com>
Licensed under the GNU AGPL <https://www.gnu.org/licenses/agpl.txt>
Check http://github.com/bbuchfink/diamond for updates.

#CPU threads: 1
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
Temporary directory: /var/folders/nf/crn9cwk14r9d_bklwmm8j7280000gn/T
Opening the database... No such file or directory
[0.00112s]
Error: Error opening file /usr/local/Cellar/anvio/5/libexec/lib/python3.6/site-packages/anvio/data/misc/COG/DB_DIAMOND/COG.dmnd

I also got nothing when doing: anvi-run-ncbi-cogs -c  Caloranaerobacte.db --search-with blastp
(no error message, just that "COGs class has no hits to process. Returning empty handed.")

I looked in the database folder - and it looks like they are empty. They just have a file called log.txt, see below. I am not sure if this is what they are supposed to look like.

-rw-r--r--  1 camilla  admin        72 27 Jun 19:34 MISSING_COG_IDs.cPickle
drwxr-xr-x  3 camilla  admin        96 27 Jun 19:33 DB_BLAST
drwxr-xr-x  3 camilla  admin        96 27 Jun 19:30 DB_DIAMOND
-rw-r--r--  1 camilla  admin       949 27 Jun 19:29 CATEGORIES.txt
-rw-r--r--  1 camilla  admin    261233 27 Jun 19:29 COG.txt
-rw-r--r--  1 camilla  admin  22043948 27 Jun 19:29 PID-TO-CID.cPickle
drwxr-xr-x  6 camilla  admin       192 27 Jun 19:10 RAW_DATA_FROM_NCBI
Camillas-MBP-2:COG camilla$ cd DB_BLAST
Camillas-MBP-2:DB_BLAST camilla$ ls
log.txt
Camillas-MBP-2:DB_BLAST camilla$ cd ../DB_DIAMOND
Camillas-MBP-2:DB_DIAMOND camilla$ ls
log.txt
Camillas-MBP-2:DB_DIAMOND camilla$

**Comment by Alopias1988** [comment] 2018-06-28 15:54
I am having similar problem with the `anvi-run-ncbi-cogs` command, this is what I am getting:

`tests-MacBook-Air:~ Laura$ anvi-run-ncbi-cogs -c /Users/Laura/Desktop/anvi/Cmaltaromaticum_SKLD3.fna.db 
COG data directory ...........................: /usr/local/Cellar/anvio/5/libexec/lib/python3.6/site-packages/anvio/data/misc/COG
COG data source ..............................: The anvi'o default.
COG data directory ...........................: /usr/local/Cellar/anvio/5/libexec/lib/python3.6/site-packages/anvio/data/misc/COG
Searching with ...............................: diamond
Directory to store temporary files ...........: /var/folders/g8/cty3222d43bdzmwb8xryztk00000gp/T/tmpkne6ebeu
Directory will be removed after the run ......: True
Sequences ....................................: 3215 sequences reported.        
FASTA ........................................: /var/folders/g8/cty3222d43bdzmwb8xryztk00000gp/T/tmpkne6ebeu/aa_sequences.fa
DIAMOND is set to be .........................: Fast
                                                                               
 Error: Pfft. Something probably went wrong with Diamond's 'blastp' since one of the
              expected output files are missing. Please check the log file here:          
              '/var/folders/g8/cty3222d43bdzmwb8xryztk00000gp/T/tmpkne6ebeu/log.txt.`


I tried updating to the earlier version of Diamond as previously suggested, but for some reason is giving me this error:

`tests-MacBook-Air:~ Laura$ brew install /Users/Laura/Desktop/anvi/v0.9.18.tar.gz 
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
heroku

Error: v0.9.18.tar.gz: /Users/Laura/Desktop/anvi/v0.9.18.tar.gz:1: Invalid char `\x1F' in expression
/Users/Laura/Desktop/anvi/v0.9.18.tar.gz:1: invalid multibyte char (UTF-8)`

I imagine this second part has to do more with something wrong in my mac and don't know how to fix it, any suggestions welcomed!

Thanks

**Comment by meren** [comment] 2018-06-28 16:02
I could reproduce this by upgrading my DIAMOND from `0.9.18` to `v0.9.22.123` via brew.

This is what I got:

```
(anvio-master) meren $ anvi-run-ncbi-cogs -c CONTIGS.db
(...)
Config Error: Pfft. Something probably went wrong with Diamond's 'blastp' since one of the
              expected output files are missing. Please check the log file here:
              '/var/folders/x5/gt4031w53fs63csv1fp0r_3w0000gn/T/tmps2ucdrjl/log.txt.


(anvio-master) meren $ cat /var/folders/x5/gt4031w53fs63csv1fp0r_3w0000gn/T/tmps2ucdrjl/log.txt
# DATE: 28 Jun 18 09:48:40
# CMD LINE: diamond blastp -q /var/folders/x5/gt4031w53fs63csv1fp0r_3w0000gn/T/tmps2ucdrjl/aa_sequences.fa -d /Users/meren/COG/DB_DIAMOND/COG -a /var/folders/x5/gt4031w53fs63csv1fp0r_3w0000gn/T/tmps2ucdrjl/diamond-search-results -t /var/folders/x5/gt4031w53fs63csv1fp0r_3w0000gn/T -p 1 --max-target-seqs 1 --evalue 1e-05
diamond v0.9.22.123 | by Benjamin Buchfink <buchfink@gmail.com>
Licensed under the GNU AGPL <https://www.gnu.org/licenses/agpl.txt>
Check http://github.com/bbuchfink/diamond for updates.

#CPU threads: 1
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
Temporary directory: /var/folders/x5/gt4031w53fs63csv1fp0r_3w0000gn/T
Opening the database...  [0.000591s]
Error: Database was built with a different version of Diamond and is incompatible.
```

So the real error was "**Database was built with a different version of Diamond and is incompatible**". Fine. Then I run this:

```
anvi-setup-ncbi-cogs -T 10 --reset
```

This run smoothly, but the previous command failed again:

```
(anvio-master) meren $ anvi-run-ncbi-cogs -c CONTIGS.db
COG data directory ...........................: /Users/meren/github/anvio/anvio/data/misc/COG
COG data source ..............................: The anvi'o default.
COG data directory ...........................: /Users/meren/github/anvio/anvio/data/misc/COG
Searching with ...............................: diamond
Directory to store temporary files ...........: /var/folders/x5/gt4031w53fs63csv1fp0r_3w0000gn/T/tmp9ge20qqc
Directory will be removed after the run ......: True
Sequences ....................................: 51 sequences reported.
FASTA ........................................: /var/folders/x5/gt4031w53fs63csv1fp0r_3w0000gn/T/tmp9ge20qqc/aa_sequences.fa
DIAMOND is set to be .........................: Fast


Config Error: Pfft. Something probably went wrong with Diamond's 'blastp' since one of the
              expected output files are missing. Please check the log file here:
              '/var/folders/x5/gt4031w53fs63csv1fp0r_3w0000gn/T/tmp9ge20qqc/log.txt.


(anvio-master) meren $ cat /var/folders/x5/gt4031w53fs63csv1fp0r_3w0000gn/T/tmp9ge20qqc/log.txt.
cat: /var/folders/x5/gt4031w53fs63csv1fp0r_3w0000gn/T/tmp9ge20qqc/log.txt.: No such file or directory
(anvio-master) meren ~/github/anvio/tests/sandbox/test-output $ cat /var/folders/x5/gt4031w53fs63csv1fp0r_3w0000gn/T/tmp9ge20qqc/log.txt
# DATE: 28 Jun 18 09:59:19
# CMD LINE: diamond blastp -q /var/folders/x5/gt4031w53fs63csv1fp0r_3w0000gn/T/tmp9ge20qqc/aa_sequences.fa -d /Users/meren/github/anvio/anvio/data/misc/COG/DB_DIAMOND/COG -a /var/folders/x5/gt4031w53fs63csv1fp0r_3w0000gn/T/tmp9ge20qqc/diamond-search-results -t /var/folders/x5/gt4031w53fs63csv1fp0r_3w0000gn/T -p 1 --max-target-seqs 1 --evalue 1e-05
diamond v0.9.22.123 | by Benjamin Buchfink <buchfink@gmail.com>
Licensed under the GNU AGPL <https://www.gnu.org/licenses/agpl.txt>
Check http://github.com/bbuchfink/diamond for updates.

#CPU threads: 1
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
Temporary directory: /var/folders/x5/gt4031w53fs63csv1fp0r_3w0000gn/T
Opening the database... No such file or directory
 [0.000777s]
Error: Error opening file /Users/meren/github/anvio/anvio/data/misc/COG/DB_DIAMOND/COG.dmnd
```

And it was truly missing from the directory:

```
(anvio-master) meren $ ls /Users/meren/github/anvio/anvio/data/misc/COG/DB_DIAMOND/COG.dmnd
ls: /Users/meren/github/anvio/anvio/data/misc/COG/DB_DIAMOND/COG.dmnd: No such file or directory
```

The question here is why DIAMOND fails to generate a DB.

SADLY, NCBI DB is missing as well:

```
(anvio-master) meren $ ls /Users/meren/github/anvio/anvio/data/misc/COG/DB_BLAST/
log.txt
```

I hope this helps.

**Comment by PlantDr430** [comment] 2018-06-29 03:03
Is it safe to assume that COGs generation is temporarily put on hold until it is determined why the Diamond and NCBI DBs are not being generated?

**Comment by meren** [comment] 2018-06-29 03:46
Hi @PlantDr430,

I think we solved the problem, and tomorrow we will release `v5.1` as a quick and small update, and let you guys know that you can install that version.

Sorry about the inconvenience :(

**Comment by PlantDr430** [comment] 2018-06-29 03:55
Wonderful news of the quick update! Thank you guys for being on top of things.

**Comment by Alopias1988** [comment] 2018-06-29 04:57
great! thanks for being so fast, looking forward to try it!

**Comment by meren** [comment] 2018-06-29 20:00
Hi everyone,

We just released a new version, `v5.1`, which solves this issue. The new packages are available through `pip` as well as `brew`.

Please let us know if you try. I am closing this issue, and I thank you for your patience and help.

**Closed by meren** 2018-06-29 20:00 UTC

**Comment by Alopias1988** [comment] 2018-06-29 21:05
Hi, I just tried it and seems like it worked with no errors, thanks!

Laura Martinez Steele
Master student | Department of Biology
California State University Long Beach
Shark Lab
________________________________
De: A. Murat Eren <notifications@github.com>
Enviado: viernes, 29 de junio de 2018 13:00
Para: merenlab/anvio
Cc: Alopias1988; Comment
Asunto: Re: [merenlab/anvio] DIAMOND issue with anvi'o v5 and anvi-run-ncbi-cogs (#894)


Hi everyone,

We just released a new version, v5.1, which solves this issue. The new packages are available through pip as well as brew.

Please let us know if you try. I am closing this issue, and I thank you for your patience and help.

**Comment by meren** [comment] 2018-06-29 21:07
Thank you very much for reporting back, Laura!

**Comment by JBuongio** [comment] 2018-06-29 21:12
Sweet! Thanks everyone. Looking forward to updating to 5.1 (the power has been out in my building all day so I have not been able to try it.)
