### ISSUE TITLE
anvi-script-checkm-tree-to-interactive -h display description from anvi-script-reformat-fasta

### ISSUE THREAD

**Issue by EricDeveaud** [merenlab/anvio#1695] opened 2021-03-12 18:46 UTC
anvio-v7 

`anvi-script-checkm-tree-to-interactive -h` display description from `anvi-script-reformat-fasta` 
see:

```
[gensoft@c1d61c16d94c anvio-7]$ anvi-script-checkm-tree-to-interactive -h 
usage: anvi-script-checkm-tree-to-interactive [-h] -t CHECKM TREE -o DIRECTORY

optional arguments                                                              
  -h, --help            show this help message and exit
  -t CHECKM TREE, --tree CHECKM TREE
                        Tree file generated by CheckM. (default: None)
  -o DIRECTORY, --output-dir DIRECTORY
                        The directory name that output files will be stored. (default
                        None)

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

🔥 Program description:

   Reformat FASTA file (remove contigs based on length, or based on given lists
   of deflines to include/exclude, and/or generate an output with simpler names)

🧀 Can consume: 

🍕 Can provide: 

🍺 More on `anvi-script-checkm-tree-to-interactive`:

   https://merenlab.org/software/anvio/help/7/programs/anvi-script-checkm-tree-to-interactive

🍻 All anvi'o programs and artifacts:

   https://merenlab.org/software/anvio/help/7

```

plus given url gives 404 error:

regards

Eric

**Comment by meren** [comment] 2021-03-12 22:40
Thanks, @EricDeveaud! We can't fix the `v7` output, but the problem is now addressed in the main repository and will be fixed in the next stable version.

Best wishes,

**Closed by meren** 2021-03-12 22:40 UTC
