### ISSUE TITLE
Errors importing --external-gene-calls when running anvi-gen-contigs-database

### ISSUE THREAD

**Issue by brymerr921** [merenlab/anvio#1398] opened 2020-04-04 19:33 UTC
Hi everyone,

I ran into an issue with `--external-gene-calls` when running `anvio-gen-contigs-database`. I happened upon this issue because I had already run prodigal on some enormous assemblies, and hoped to bypass the computational time and just import the prodigal files directly into my contigs database using `--external-gene-calls`.

However, there are several issues with this. Here is what I understand so far.
1. Prodigal (in `--meta` mode, which is on by default as long as a default translation table is not provided, [see code](https://github.com/merenlab/anvio/blob/ed705f9e8476db1dcbef49948b337308a570efc7/anvio/drivers/prodigal.py#L130)) evaluates each contig independently to determine which is the best translation table.
2. anvi'o then imports the start and stop position, the direction, whether the gene is complete or incomplete, and the Prodigal-reported amino acid sequence into the contigs database, but does not attempt to translate gene call (start, stop, direction) from the contig sequence into the protein sequence.

This becomes an issue when attempting to import prodigal-generated external gene calls (using the `--meta` flag) back into anvi'o using `anvi-gen-contigs-database --external-gene-calls` because:  

3. anvi'o attempts to translate the gene calls (start, stop, direction) into an amino acid sequence, but there are no columns in the `--external-gene-calls` file to specify which translation table ought to be used for each gene. Therefore, some gene calls using a different translation table (such as `4`) will show errors because they contain internal stop codons relative to translation table `11`, which, I think, is what is used by default to translate `--external-gene-calls` into amino acid sequences.

4. This problem is also apparent when running:
  a. `anvi-gen-contigs-database` without specifying `--external-gene-calls` (so letting it run in `prodigal --meta`)
  b. `anvi-export-gene-calls --gene-caller prodigal -o gene_calls.txt`
  c. `anvi-gen-contigs-database --external-gene-calls -o gene_calls.txt`

4c shows an error due to internal stop codons on all genes where prodigal used translation table `4` (as just one example) in step 4a.

Some ideas for this (and other potential issues involving complex eukaryote gene calling) might be to add the ability to import a translation table column and/or amino acid sequence column (as is generated with `anvi-export-gene-calls`) from a provided `--external-gene-calls` file.

Hopefully I'm not too far off, and that this is helpful. This isn't a huge issue for me right now (I ended up just letting anvi'o re-run prodigal) but I wanted to bring it up.

Best,
Bryan

Related issue in google groups:
https://groups.google.com/forum/#!msg/anvio/f1xg6dxB9qE/WL6Vg2IxAAAJ

**Comment by ekiefl** [comment] 2020-04-04 21:54
If I'm understanding the problem correctly, are you saying that `--prodigal-translation-table` does not work because prodigal decides upon a translation table on a per-contig basis, and therefore a blanketed "--prodigal-translation-table" does not work?

**Comment by meren** [comment] 2020-04-05 15:20
@ekiefl, I think the problem is `anvi-export-gene-calls` reports amino acid sequences, but when `anvi-gen-contigs-database` is run with external gene calls using the output of `anvi-export-gene-calls`, it doesn't use those amino acid sequences, instead tries to translate the DNA sequence found on the contig based on gene start/stop positions in the file.

Can please someone tell me if I'm wrong?

**Comment by brymerr921** [comment] 2020-04-06 18:53
@ekiefl, that's correct. Prodigal in `--meta` mode decides the translation table on a per-contig basis. But, if a user already has their correctly-translated amino acid sequences, then ......

@meren... looks like I've gone and made an issue about nothing! I had absolutely no idea that you can provide an amino acid sequence under the column `aa_sequence` in a table to import using `anvi-gen-contigs-database --external-gene-calls`!!!  This is fantastic news. Can you add this to the help documentation and documentation and the example file (https://bit.ly/2qEEHuQ)?  I previously thought that these were the only columns allowed:
```
anvi-gen-contigs-db -h
  --external-gene-calls GENE-CALLS
                        A TAB-delimited file to utilize external gene calls.
                        The file must have these columns: 'gene_callers_id' (a
                        unique integer number for each gene call, start from
                        1), 'contig' (the contig name the gene call is found),
                        'start' (start position, integer), 'stop' (stop
                        position, integer), 'direction' (the direction of the
                        gene open reading frame; can be 'f' or 'r'), 'partial'
                        (whether it is a complete gene call, or a partial one;
                        must be 1 for partial calls, and 0 for complete
                        calls), 'source' (the gene caller), and 'version' (the
                        version of the gene caller, i.e., v2.6.7 or v1.0). An
                        example file can be found via the URL
                        https://bit.ly/2qEEHuQ
```

If a user simply provides the `aa_sequence` column it will solve the changing translation table issue, and also might actually solve the eukaryote gene calling issue by just allowing users to provide their own translated eukaryote amino acid sequences in their `--external-gene-calls` file.

**Comment by meren** [comment] 2020-04-06 19:03
Our online documentation is in a miserable state :/ I will add a note :)

**Comment by cdiazmun** [comment] 2020-04-08 13:43
Hello everyone, coming from the parallel issue in the Anvi'o forum (https://groups.google.com/forum/#!forum/anvio), I can see how it makes sense the strategy of @brymerr921 . Unfortunately, I couldn't run it myself because my informatic skills are not enough to extract the protein sequence of all genes from the AUGUSTUS output file (I tried with grep, sed, cut, ...). It's so close, but so far at the same time. Thus, if you add the ninth column...is it needed to set the column 'partial' to 1 so anvio doesn't try to translate the sequence? or it detects automatically the 'aa_sequence' column?

Listening to the advices of @meren , I upload here the following files in case someone wants to explore more into the issue:
1) Saccharomyces cerevisiae S288C genome (the reference genome):
[S288C_genome.zip](https://github.com/merenlab/anvio/files/4450784/S288C_genome.zip)

2) AUGUSTUS output file:
[S288C_aug_out.zip](https://github.com/merenlab/anvio/files/4450792/S288C_aug_out.zip)

3) Reformated external gene caller file:
[S288C_gene_calls.txt](https://github.com/merenlab/anvio/files/4450796/S288C_gene_calls.txt)

I hope it is helpful!

**Comment by meren** [comment] 2020-04-08 21:38
Hey @cdiazmun,

There is now a new script for this, and this is what happens when I run it on files you sent us:

```
anvi-script-augustus-output-to-external-gene-calls -i S288C.gff \
                                                   -o external_gene_calls.txt

Num genes found ..............................: 5,462
Anvi'o external genes file output ............: external_gene_calls.txt
```

And then,

```
anvi-gen-contigs-database -f S288C_genome_nomit.fasta \
                          --external-gene external_gene_calls.txt \
                          -o S288C.db


Name .........................................: S288C_genome_nomit
Description ..................................: No description is given
External gene calls ..........................: 5462 gene calls recovered and will be processed.
Split Length .................................: 20,000
K-mer size ...................................: 4
Skip gene calling? ...........................: False
External gene calls provided? ................: True
External gene calls file have AA sequences? ..: True
Ignoring internal stop codons? ...............: False
Splitting pays attention to gene calls? ......: True
Contigs with at least one gene call ..........: 16 of 16 (100.0%)
Contigs database .............................: A new database, c.db, has been created.
Number of contigs ............................: 16
Number of splits .............................: 595
Total number of nucleotides ..................: 12,071,326
Gene calling step skipped ....................: False
Splits broke genes (non-mindful mode) ........: False
Desired split length (what the user wanted) ..: 20,000
Average split length (wnat anvi'o gave back) .: 20,28
```

Tadaa:

```
anvi-db-info c.db

DB Info (no touch)
===============================================
Database Path ................................: S288C.db
Description ..................................: [Not found, but it's OK]
Type .........................................: contigs
Version ......................................: 14


DB Info (no touch also)
===============================================
project_name .................................: S288C
contigs_db_hash ..............................: hashdb0bffb4
split_length .................................: 20000
kmer_size ....................................: 4
num_contigs ..................................: 16
total_length .................................: 12071326
num_splits ...................................: 595
gene_level_taxonomy_source ...................: None
gene_function_sources ........................: None
genes_are_called .............................: 1
splits_consider_gene_calls ...................: 1
scg_taxonomy_was_run .........................: 0
creation_date ................................: 1586380077.21674

* Please remember that it is never a good idea to change these values. But in some
cases it may be absolutely necessary to update something here, and a programmer
may ask you to run this program and do it. But even then, you should be very
skeptical. For instance, if the programmer asks you to change the values for
'num_contigs', or 'kmer_size', it would mean that they likely hate you and want
you to fail. So please be extremely careful changing any of these values.

AVAILABLE GENE CALLERS
===============================================
* 'AUGUSTUS' (5,462 gene calls)


AVAILABLE HMM SOURCES
===============================================
* This contigs db does not have HMMs :/
```

The script is [here](https://github.com/merenlab/anvio/blob/master/sandbox/anvi-script-augustus-output-to-external-gene-calls) and you can download and use it in your anvi'o environment the following way if you are not on `master`:

```
wget https://raw.githubusercontent.com/merenlab/anvio/master/sandbox/anvi-script-augustus-output-to-external-gene-calls
chmod +x anvi-script-augustus-output-to-external-gene-calls
./anvi-script-augustus-output-to-external-gene-calls --help
```

Please let us know if it works. Testing this is on you :)


Best,

**Comment by cdiazmun** [comment] 2020-04-09 09:20
Okay that was much more than what I expected! I have no words to express my thanks! 

So, I downloaded the script and run it. First, `--anvi-gen-contigs-database` gave me a config error because there were more columns than expected and I assumed it was due to the anvio version, as I was still working on v5.5. So I updated to the v6.2 and it worked perfectly!

Thank you very much!

**Comment by ekiefl** [comment] 2020-12-07 16:35
As per @brymerr921's issue, this is now resolved by adding an additional column to the external gene calls file in which the amino acid sequence can be supplied. If present, anvi'o will not attempt its own translation of the DNA sequence.

**Closed by ekiefl** 2020-12-07 16:35 UTC
