### ISSUE TITLE
Error of anvi-get-enriched-functions-per-pan-group

### ISSUE THREAD

**Issue by anjohnlee** [merenlab/anvio#1320] opened 2019-12-28 04:04 UTC
THIS *IS* A TECHNICAL ISSUE
---------------------------------------------

```
#anvi-self-test --version
(anvio-6.1) dell@dell-Precision-Tower-7910:~$ anvi-self-test --version
Anvi'o version ...............................: esther (v6.1)
Profile DB version ...........................: 31
Contigs DB version ...........................: 14
Pan DB version ...............................: 13
Genome data storage version ..................: 6
Auxiliary data storage version ...............: 2
Structure DB version .........................: 1
```

---------------------------------------------
Hi Meren, 
    I'm using Ubuntu 18.04 LTS on dell-Precision-Tower-7910. Anvi'o 6.1 was installed by conda.
    With anvi'o, I created GENOMES.db and PAN.db, imported functions in a simple matrix by "anvi-import-functions", and imported layers_additional_data. All are fine untill doing "anvi-get-enriched-functions-per-pan-group":

```
anvi-get-enriched-functions-per-pan-group -p Arenibacter-PAN.db \
  -g Arenibacter-GENOMES.db  \
  --category-variable clade \
  --annotation-source eggnog \
  -o enriched-functions-B1 \
  --functional-occurrence-table-output functions-occurrence-frequency-B1
```

My "Error log" is as below:

![image](https://user-images.githubusercontent.com/33259297/71538590-ab918600-2968-11ea-9b42-5e515284b4ec.png)

And the log file "/tmp/tmpdyqm_164" is like this:

![image](https://user-images.githubusercontent.com/33259297/71538613-117e0d80-2969-11ea-9290-c906304f6c06.png)

Actually, the samle error was also obtained when using Anvi'o 6.0 to do the same work, before I installed Anvi'o 6.1 with good wishes.

Looking forward to your reply~

Anzhang Li

**Comment by meren** [comment] 2019-12-28 14:41
Now did you install anvi'o, Anzhang?

It looks like even @mooreryan's workaround for tidyr did not work for you. This is most likely due to the versions of libraries in your R environment. Please follow Ryan's message here and send us the resulting output when you run his script:

https://github.com/merenlab/anvio/issues/1248#issuecomment-538607081

Maybe someone can immediately see what is the problem.

Best,

**Comment by anzhangli84** [comment] 2020-01-01 03:09
Happy 2020, Guys~
I am lonely in lab and pretty depressed because of the same error。

1. I installed anvi'o 6.1 by conda.
2. I reinstalled R.    Now, R version 3.5.1 (2018-07-02); nickname: Feather Spray
3. I installed the R packages including qvalue, tidyr v1.0.0.
4. Run `anvi-get-enriched-functions-per-pan-group -p Arenibacter-PAN.db  -g Arenibacter-GENOMES.db  --category-variable clade   --annotation-source eggnog  -o enriched-functions  --functional-occurrence-table-output functions-occurrence-frequency`
   
    Got the same error:
>   Config Error: It looks like something went wrong during the functional enrichment analysis. We              don't know what happened, but this log file could contain some clues: /tmp/tmpjl9eeyct 

The log file  /tmp/tmpjl9eeyct  is as:

> DATE: 01 Jan 20 10:38:45
> CMD LINE: anvi-script-run-functional-enrichment-stats --input /tmp/tmpcws5awsk --output >/home/dell/anvi2/enriched-functions-B1
>tidyr major version >= 1.  Using nest_legacy.
>Parsed with column specification:
>cols(
  >eggnog = col_character(),
 > function_accession = col_character(),
 > gene_clusters_ids = col_character(),
  >associated_groups = col_character(),
>  p_A1 = col_double(),
 > p_B2 = col_double(),
 > N_A1 = col_double(),
>  N_B2 = col_double()
>)
>Error in smooth.spline(lambda, pi0, df = smooth.df) : 
 > missing or infinite values in inputs are not allowed
>Calls: %>% ... mutate_impl -> <Anonymous> -> pi0est -> smooth.spline
>Execution halted

5. Did't found "anvi-run-enrichment-analysis" in /usr/miniconda3/bin, so copied the code of @mooreryan (https://github.com/merenlab/anvio/blob/2c9179f037b43502901582ad7eea61f5dbfc3131/bin/anvi-run-enrichment-analysis.R#L81) and changed line 81 as "nest_legacy %>%".
    
Then, run  `anvi-run-enrichment-analysis --input /home/dell/anvi2/functions-occurrence-frequency-B1 --output Functional_enrichment_2_groups.txt`
Got errors like:
>(anvio-6.1) dell@dell-Precision-Tower-7910:~$ anvi-run-enrichment-analysis --input /home/dell/anvi2>/functions-occurrence-frequency-B1 --output Functional_enrichment_2_groups.txt
>Parsed with column specification:
>cols(
>  X1 = col_character(),     ####### red color
>  AGUO = col_double(),
>  AJC631 = col_double(),
 > AUBA3199 = col_double(),
>  AalgicolaC21 = col_double(),
>  AalgicolaSMS7 = col_double(),
>  AalgicolaTG409 = col_double(),
>  AantarcticusR18H21 = col_double(),
>  AcatalasegensP308H10 = col_double(),
>  AcertesiiDSM19833 = col_double(),
>  AechinorumDSM23522 = col_double(),
>  AhampyeongensisJCM17788 = col_double(),
>  AlatericiusDSM15913 = col_double(),
>  AnanhaiticusCGMCC18863 = col_double(),
>  ApalladensisDSM17539 = col_double(),
>  AspAK53 = col_double(),
>  AspARW7G5Y1 = col_double(),
>  AspP308M17 = col_double(),
>  AtroitsensisDSM19835 = col_double()
>)
>Warning message:
>Missing column names filled in: 'X1' [1] 
>Warning message:
>In min(.) : no non-missing arguments to min; returning Inf
>Error in if (G%%1 != 0) { : missing value where TRUE/FALSE needed
>Execution halted

Tried to run  `anvi-run-enrichment-analysis --input /tmp/tmpcws5awsk --output Functional_enrichment_2_groups.txt`
 Got errors like:
>(anvio-6.1) dell@dell-Precision-Tower-7910:~$ anvi-run-enrichment-analysis --input >/tmp/tmpcws5awsk --output Functional_enrichment_2_groups.tx
>Parsed with column specification:
>cols(
>  eggnog = col_character(),                  ######### red color
>  function_accession = col_character(),      ######### red color
>  gene_clusters_ids = col_character(),       ######### red color
>  associated_groups = col_character(),       ######### red color
>  p_A1 = col_double(),
>  p_B2 = col_double(),
>  N_A1 = col_double(),
>  N_B2 = col_double()
>)
>Error in smooth.spline(lambda, pi0, df = smooth.df) : 
>  missing or infinite values in inputs are not allowed
>Calls: %>% ... mutate_impl -> <Anonymous> -> pi0est -> smooth.spline
>Execution halted

6. Found the script "anvi-script-run-functional-enrichment-stats" included in /usr/miniconda3/bin.
So run `anvi-script-run-functional-enrichment-stats --input /home/dell/anvi2/functions-occurrence-frequency-B1 --output Functional_enrichment_2_groups.txt` and got error like:

>(anvio-6.1) dell@dell-Precision-Tower-7910:~$ anvi-script-run-functional-enrichment-stats --input >/home/dell/anvi2/functions-occurrence-frequency-B1 --output Functional_enrichment_2_groups.txt
>tidyr major version >= 1.  Using nest_legacy.
>Parsed with column specification:
>cols(
>  X1 = col_character(),   ######### red color
>  AGUO = col_double(),
>  AJC631 = col_double(),
>  AUBA3199 = col_double(),
>  AalgicolaC21 = col_double(),
>  AalgicolaSMS7 = col_double(),
>  AalgicolaTG409 = col_double(),
>  AantarcticusR18H21 = col_double(),
>  AcatalasegensP308H10 = col_double(),
>  AcertesiiDSM19833 = col_double(),
>  AechinorumDSM23522 = col_double(),
>  AhampyeongensisJCM17788 = col_double(),
>  AlatericiusDSM15913 = col_double(),
>  AnanhaiticusCGMCC18863 = col_double(),
 > ApalladensisDSM17539 = col_double(),
>  AspAK53 = col_double(),
>  AspARW7G5Y1 = col_double(),
>  AspP308M17 = col_double(),
>  AtroitsensisDSM19835 = col_double()
>)
>Warning message:
>Missing column names filled in: 'X1' [1] 
>Warning message:
>In min(.) : no non-missing arguments to min; returning Inf
>Error in if (G%%1 != 0) { : missing value where TRUE/FALSE needed
>Execution halted

Then run `anvi-script-run-functional-enrichment-stats --input /tmp/tmpcws5awsk --output Functional_enrichment_2_groups.txt` and got error like:

>(anvio-6.1) dell@dell-Precision-Tower-7910:~$ anvi-script-run-functional-enrichment-stats --input >/tmp/tmpcws5awsk --output Functional_enrichment_2_groups.txt
>tidyr major version >= 1.  Using nest_legacy.
>Parsed with column specification:
>cols(
>  eggnog = col_character(),   ######### red color
>  function_accession = col_character(),    ######### red color
>  gene_clusters_ids = col_character(),     ######### red color
>  associated_groups = col_character(),     ######### red color
>  p_A1 = col_double(),
>  p_B2 = col_double(),
>  N_A1 = col_double(),
>  N_B2 = col_double()
>)
>Error in smooth.spline(lambda, pi0, df = smooth.df) : 
>  missing or infinite values in inputs are not allowed
>Calls: %>% ... mutate_impl -> <Anonymous> -> pi0est -> smooth.spline
>Execution halted


That's all. 
I only learned biology and know nothing about programming, so I am sorry if I made rookie mistakes.
New year, wish good news.

**Comment by meren** [comment] 2020-01-01 03:21
Sorry guys, I hope @ShaiberAlon or @mooreryan will have something to suggest. The holiday season is not the time to expect fast responses :)

**Comment by anjohnlee** [comment] 2020-01-01 04:23
Thank you Meren. 
Yeah, wish everyone enjoy the holiday. Not urgent things.

**Comment by ShaiberAlon** [comment] 2020-01-01 04:41
Hi @anjohnlee ,

When you run the enrichment analysis, there is a temporary file that is created. It is the “functional occurrence summary “ and anvio tells you what is the path to that file (look for example at the first screenshot you shared on this page). Could you please send me that file via [email](mailto:alon.shaiber@gmail.com)?

I want to see if I can reproduce your error.

**Comment by anzhangli84** [comment] 2020-01-01 05:10
Hi, Alon~
   Happy new year. Sorry for bothering you at the holiday. Please, needn't test it today. It's not urgent.
   The temporary file was attached with this mail. Thank you in advance.
Best wishes.




Anzhang Li
86-20-87137635
State Key Laboratory of Applied Microbiology Southern China

Guangdong  Institute  of  Microbiology



On 1/1/2020 12:41，Alon Shaiber<notifications@github.com> wrote：

Hi @anjohnlee ,

When you run the enrichment analysis, there is a temporary file that is created. It is the “functional occurrence summary “ and anvio tells you what is the path to that file (look for example at the first screenshot you shared on this page). Could you please send me that file via email?

I want to see if I can reproduce your error.

**Comment by ShaiberAlon** [comment] 2020-01-01 05:21
Hi @anjohnlee , the attachment didn’t go through. Could you please send it to me in a separate email to my address: alon.shaiber@gmail.com

Happy New Year!

**Comment by anjohnlee** [comment] 2020-01-01 05:25
Hi, Alon! the file has been sent to your gmail address.

**Comment by ShaiberAlon** [comment] 2020-01-02 20:30
@anjohnlee , after looking at your file I see what is the problem. You functions don't have accession numbers. This is mandatory in order to run `anvi-get-enriched-functions-per-pan-group`.

But it is totally our fault for not catching this in our sanity checks and raising a proper error.

How come the functions don't have accessions associated with them? As far as I can remember eggnog provides accession numbers.

If you want there is a way around this for now: you can take the "functional occurrence summary" and provide some unique "fake" accession value for each function. Then you can take the file and use it as an input for `anvi-script-run-functional-enrichment-stats`. I have done this with your file and it worked. I will send you these results in a private email.

**Comment by anzhangli84** [comment] 2020-01-04 03:37
Hi, Alon,
    You are awesome! Thanks very much. It worked when I offered "fake" accession numbers. 
    I implemented the annotation via eggNOG 5.0 online interface (http://eggnog-mapper.embl.de). 
    It's my mistake that I didn't extract the column "seed_eggNOG_ortholog" from the annotation file and moved it to the TAB-delimited input matrix of anvi'o as accession numbers. Because, to be frank, I was not sure if these "seed_eggNOG_ortholog" values are accession numbers available to Anvi'o. To avoid trouble whenever possible, I leave it blank. And interestingly I got a big trouble.....   
    Thanks again~


Anzhang Li
86-20-87137635
State Key Laboratory of Applied Microbiology Southern China

Guangdong  Institute  of  Microbiology



On 1/3/2020 04:30，Alon Shaiber<notifications@github.com> wrote：

@anjohnlee , after looking at your file I see what is the problem. You functions don't have accession numbers. This is mandatory in order to run anvi-get-enriched-functions-per-pan-group.

But it is totally our fault for not catching this in our sanity checks and raising a proper error.

How come the functions don't have accessions associated with them? As far as I can remember eggnog provides accession numbers.

If you want there is a way around this for now: you can take the "functional occurrence summary" and provide some unique "fake" accession value for each function. Then you can take the file and use it as an input for anvi-script-run-functional-enrichment-stats. I have done this with your file and it worked. I will send you these results in a private email.

**Comment by ShaiberAlon** [comment] 2020-01-04 03:39
Hi Anzhang,

I'm glad you reached out with your question, and I'm glad this now worked
for you.
Good luck with the rest of your analysis!

Best,
Alon

**Comment by mooreryan** [comment] 2020-01-04 18:22
For reference, I found the place in the code where the from which the `smooth.spline` error actually bubbles up.  It's in the [anvi-script-run-functional-enrichment-stats](https://github.com/merenlab/anvio/blob/master/sandbox/anvi-script-run-functional-enrichment-stats) script, right here: 

https://github.com/merenlab/anvio/blob/a2605a160ffb0b181e716ee532548cf90f12980c/sandbox/anvi-script-run-functional-enrichment-stats#L141

So that means there are missing or infinite values should be in the `unadjusted_p_value` variable.

**Comment by ShaiberAlon** [comment] 2020-01-04 19:27
Hi Ryan,

Thank you for taking a look, but I believe that this entire problem is
because of this line:

https://github.com/merenlab/anvio/blob/a2605a160ffb0b181e716ee532548cf90f12980c/sandbox/anvi-script-run-functional-enrichment-stats#L131

The fit is made by grouping functions according to the accession, but if
accessions are missing then all functions are grouped together, which
eventually results in the missing or infinite p values that smooth.spline
is complaining about.

I think we should keep on grouping according to accessions since these are
by definition unique, while function names are not always unique from what
I have seen.

I will add a sanity check so that if accessions are missing them a proper
error would notify the user that they are required.

Please let me know if you have any comments/questions.

Thanks!

**Comment by ShaiberAlon** [comment] 2020-01-04 19:28
Closing this issue, since I opened a more focused issue to address the required exception that I mentioned above.

**Closed by ShaiberAlon** 2020-01-04 19:28 UTC
