### ISSUE TITLE
Anvi'o gives cryptic error when there are no gene calls in the FASTA file

### ISSUE THREAD

**Issue by sipesk** [merenlab/anvio#874] opened 2018-06-19 13:50 UTC
Hi!

**ANVI SELF TEST OUTPUT**
Anvi'o version ...............................: 4
Profile DB version ...........................: 23
Contigs DB version ...........................: 10
Pan DB version ...............................: 8
Genome data storage version ..................: 6
Auxiliary data storage version ...............: 2

ISSUE:

%%**When I run**

(anvio-4) barbara-lloydlab@lloydbarbara:~/Desktop/KBaseKatie/anvio_concot_all_bins_and_outgroups$ anvi-script-FASTA-to-contigs-db KS10_prokka.fa

%%I get this

:: INPUT DIR: /home/barbara-lloydlab/Desktop/KBaseKatie/anvio_concot_all_bins_and_outgroups, FNAME: KS10_prokka ...

:: RENAMING CONTIGS ...

Input ........................................: /home/barbara-lloydlab/Desktop/KBaseKatie/anvio_concot_all_bins_and_outgroups/KS10_prokka.fa
Output .......................................: /home/barbara-lloydlab/Desktop/KBaseKatie/anvio_concot_all_bins_and_outgroups/KS10_prokka-clean.fa
Minimum length ...............................: 0
Total num contigs ............................: 30
Total num nucleotides ........................: 3,655
Contigs removed ..............................: 0 (0.00% of all)
Nucleotides removed ..........................: 0 (0.00% of all)
Deflines simplified ..........................: True

:: GENERATING THE CONTIGS DB ...

Input FASTA file .............................: /home/barbara-lloydlab/Desktop/KBaseKatie/anvio_concot_all_bins_and_outgroups/KS10_prokka-clean.fa
Name .........................................: KS10_prokka
Description ..................................: No description is given
Split Length .................................: 20,000                                                                          
K-mer size ...................................: 4
Skip gene calling? ...........................: False
External gene calls provided? ................: None
Ignoring internal stop codons? ...............: False
Splitting pays attention to gene calls? ......: False

Finding ORFs in contigs
===============================================
Genes ........................................: /tmp/tmp6dm32mx1/contigs.genes
Amino acid sequences .........................: /tmp/tmp6dm32mx1/contigs.amino_acid_sequences
Log file .....................................: /tmp/tmp6dm32mx1/00_log.txt
[19 Jun 18 09:30:44 Processing] Processing gene calls ...                                                                      Traceback (most recent call last):
  File "/home/barbara-lloydlab/virtual-envs/anvio-4/bin/anvi-gen-contigs-database", line 50, in <module>
    a.create(args)
  File "/home/barbara-lloydlab/virtual-envs/anvio-4/lib/python3.5/site-packages/anvio/dbops.py", line 2636, in create
    gene_calls_tables.call_genes_and_populate_genes_in_contigs_table()
  File "/home/barbara-lloydlab/virtual-envs/anvio-4/lib/python3.5/site-packages/anvio/tables/genecalls.py", line 232, in call_genes_and_populate_genes_in_contigs_table
    gene_calls_dict, amino_acid_sequences = self.run_gene_caller(gene_caller)
  File "/home/barbara-lloydlab/virtual-envs/anvio-4/lib/python3.5/site-packages/anvio/tables/genecalls.py", line 255, in run_gene_caller
    gene_calls_dict, amino_acid_sequences = gene_caller.process()
  File "/home/barbara-lloydlab/virtual-envs/anvio-4/lib/python3.5/site-packages/anvio/genecalling.py", line 58, in process
    gene_calls_dict, amino_acid_sequences_dict = gene_caller.process(self.fasta_file_path, output_dir)
  File "/home/barbara-lloydlab/virtual-envs/anvio-4/lib/python3.5/site-packages/anvio/drivers/prodigal.py", line 130, in process
    fasta = fastalib.SequenceSource(self.amino_acid_sequences_in_contigs)
  File "/home/barbara-lloydlab/virtual-envs/anvio-4/lib/python3.5/site-packages/anvio/fastalib.py", line 103, in __init__
    raise FastaLibError("File '%s' does not seem to be a FASTA file." % self.fasta_file_path)
anvio.fastalib.FastaLibError: Fasta Lib Error: File '/tmp/tmp6dm32mx1/contigs.amino_acid_sequences' does not seem to be a FASTA file.

The command is not creating the .h5 file that is needed to mirgrate the db from 9 to 10. And anvio will not read the .db on the external-genomes.txt file.

Thanks for the help !

**Comment by meren** [comment] 2018-06-19 15:07
Would you mind sending your FASTA file?

**Comment by meren** [comment] 2018-06-19 15:09
Oh, never mind. I could reproduce this.

**Comment by meren** [comment] 2018-06-19 15:21
The problem is your FASTA file does not contain any sequences with at least one gene call. I fixed in the master. 

You can run `anvi-gen-contigs-database` with the `--skip-gene-calling` flag. but then you will not be able to do any pangenomic analyses or HMM-based inquiries.

**Closed** 2018-06-19 15:21 UTC

**Comment by sipesk** [comment] 2018-06-19 15:31
Hero ! Thanks !
