### ISSUE TITLE
Problem in finding gene functions

### ISSUE THREAD

**Issue by tomkolan** [merenlab/anvio#2116] opened 2023-09-15 15:35 UTC
Hi,

I’m using anvio with genebank files (thus the ncbi gene caller), for some reason which I couldn’t find, when I searched some of the genes/functions using their accession numbers it seems that they are missing though they exist in the genebank files.

Do you know a possible reason for that?
How can it be fixed?

Thanks 🙏

**Comment by metehaansever** [comment] 2023-09-15 15:45
Hey @tomkolan  Which program do you use? If you show us your terminal it may help us understand where the problem is.

**Comment by tomkolan** [comment] 2023-09-15 15:58
Thanks for your response. I am using anvi-script-process-genbank. After I have completed the process (including pan genome and ANIs) I’m using the interactive interface. I can find most of the gene functions, however some of them are not there. When I opened the genome-storage-function files, these accession numbers are indeed missing (but they can be found in the genebank files).

**Comment by meren** [comment] 2023-09-17 09:35
@tomkolan, you didn't respond to the questions in the issue template. which requires me to ask the same questions that were already in the issue template. I'll close this issue now. please feel free to start another one, fill out the template properly, and consider including a completely reproducible example in it (i.e., put all your the relevant input files in a directory, gzip it, and upload it somewhere and send us a download link).

**Closed by meren** 2023-09-17 09:35 UTC
