### ISSUE TITLE
[BUG] anvi-script-visualize-split-coverages cannot make a fill chart using both --xlim flag and a samples.txt

### ISSUE THREAD

**Issue by watsonar** [merenlab/anvio#1481] opened 2020-08-06 16:16 UTC
## Short description of the problem

When making a fill chart (the default chart type) with `anvi-script-visualize-split-coverages`, you can either use the `--xlim` flag or a `samples.txt`, but not both at the same time without encountering an error. Adding `--chart-type line` fixes the issue.

## anvi'o version

```
Anvi'o version ...............................: esther (v6.2-master)
Profile DB version ...........................: 34
Contigs DB version ...........................: 18
Pan DB version ...............................: 14
Genome data storage version ..................: 7
Auxiliary data storage version ...............: 2
Structure DB version .........................: 2
Kegg Modules DB version ......................: 2
```

## System info

MacOS Catalina, and I installed anvi'o via the [youre-a-wizard-arry method](http://merenlab.org/2016/06/26/installation-v2/#following-the-active-codebase-youre-a-wizard-arry
) on the anvi'o installation page.

## Detailed description of the issue

When I run this command:
```
anvi-script-visualize-split-coverages -i coverages.txt \
                                      -o coverages.pdf \
                                      -d variability.txt \
                                      -w 30 \
                                      -s samples.txt \
                                      --snv-marker-transparency 1 \
                                      --snv-wobble-pos-color=#749637 \
                                      --snv-non-wobble-pos-color=#e33e33 \
                                      --snv-intergenic-color=#999999 \
                                      --snv-marker-width=0.1 \
                                      --free-y-scale
```
I get the desired output, split and colored according to my specifications in the `samples.txt` file, and no errors.

But when I run this command (adding the --xlim flag):
```
anvi-script-visualize-split-coverages -i coverages.txt \
                                      -o coverages.pdf \
                                      -d variability.txt \
                                      -w 30 \
                                      -s samples.txt \
                                      --snv-marker-transparency 1 \
                                      --snv-wobble-pos-color=#749637 \
                                      --snv-non-wobble-pos-color=#e33e33 \
                                      --snv-intergenic-color=#999999 \
                                      --snv-marker-width=0.1 \
                                      --free-y-scale \
                                      -x 2287,4232
```
I get this output and error message:
```
I, [2020-08-05 17:11:24.720491 #95741] INFO -- Checking options
I, [2020-08-05 17:11:24.742883 #95741] INFO -- Parsing input data
I, [2020-08-05 17:11:44.002444 #95741] INFO -- Largest sample has 69293 points
I, [2020-08-05 17:11:44.002540 #95741] INFO -- Compressing samples.  Window size is 207
I, [2020-08-05 17:11:44.002584 #95741] INFO -- Total data points before compression: 4504045
I, [2020-08-05 17:12:05.543009 #95741] INFO -- Total data points after compression: 21840
I, [2020-08-05 17:12:05.543143 #95741] INFO -- Coverage will be capped at 1000
I, [2020-08-05 17:12:05.667414 #95741] INFO -- Sample_data given.  Adjusting split_coverages.
I, [2020-08-05 17:12:05.669567 #95741] INFO -- Not all samples in the split coverages file were present in the sample data file.
W, [2020-08-05 17:12:05.681073 #95741] WARN -- Some of the samples listed in the SNV data file were not also in the split coverages file.  These will not be included in the SNV data.
I, [2020-08-05 17:12:05.724884 #95741] INFO -- Making coverage plots
I, [2020-08-05 17:12:05.830516 #95741] INFO -- Writing coverage plots
Error: Aesthetics must be either length 1 or the same as the data (9): fill
Backtrace:
     █
  1. └─global::write_plot(cov_plot, dat, opts)
  2.   ├─base::print(plt$plot)
  3.   └─ggplot2:::print.ggplot(plt$plot)
  4.     ├─ggplot2::ggplot_build(x)
  5.     └─ggplot2:::ggplot_build.ggplot(x)
  6.       └─ggplot2:::by_layer(function(l, d) l$compute_geom_2(d))
  7.         └─ggplot2:::f(l = layers[[i]], d = data[[i]])
  8.           └─l$compute_geom_2(d)
  9.             └─ggplot2:::f(..., self = self)
 10.               └─self$geom$use_defaults(data, self$aes_params, modifiers)
 11.                 └─ggplot2:::f(..., self = self)
 12.                   └─ggplot2:::check_aesthetics(params[aes_params], nrow(data))
In addition: Warning message:
Removed 327 rows containing missing values (position_stack).
Execution halted
```

Specifying `--chart-type line` fixes the issue, but it would be nice to be able to make a fill chart with these specifications, too. :)

**Comment by mooreryan** [comment] 2020-08-06 17:31
I didn't even realize there was an `--xlim` option for this script! But I went back to check and (pretty sure) I found the problem. (pinging @ekiefl since he added the `xlim` option)

## Pretty sure the problem is this

The problem when using `xlim` is this (from [ggplot2 reference](https://ggplot2.tidyverse.org/reference/lims.html)):

> By default, any values outside the limits specified are replaced with NA. Be warned that this will remove data outside the limits and this can produce unintended results. For changing x or y axis limits without dropping data observations, see coord_cartesian().

So when using `xlim` anything outside the x-limits region is getting dropped.  

This will be a problem if a sample file is given.  If there is a sample file, each x value will be assigned a specific color (regardless of whether colors are specified in the samples file or not): 

https://github.com/merenlab/anvio/blob/d1a1c5421ff94ae963f69983ab98cfbea9e1ec21/sandbox/anvi-script-visualize-split-coverages#L590

These colors get passed straight to the `geom` function here:

https://github.com/merenlab/anvio/blob/d1a1c5421ff94ae963f69983ab98cfbea9e1ec21/sandbox/anvi-script-visualize-split-coverages#L940

So when the xlims get set here

https://github.com/merenlab/anvio/blob/d1a1c5421ff94ae963f69983ab98cfbea9e1ec21/sandbox/anvi-script-visualize-split-coverages#L988

The data outside the xlims is dropped, but the `fill` aesthetic set above still has the number of values as the original number of x values (rather than the subset specified with `xlim`).  (pretty sure at least).

Oh and the reason that xlims works for the line chart but not for the area chart, is that the line chart doesn't actually use the `fill` aesthetic, so it is ignored.  That should probably be fixed as well, but that's another issue!

## Potential solution

Either, set the x limits using `coord_cartesian` (probably the best option), or, use the x limits given on the command line to adjust `split_coverages_subset$sample_color` to the correct length (probably an annoying option).

**Comment by ekiefl** [comment] 2020-08-06 17:43
@mooreryan, thanks for identifying the problem. I didnt run into this error when adding the xlim option :/

@watsonar would you be interested in replacing what I did with `coord_cartesian` and seeing if it works?

**Comment by watsonar** [comment] 2020-08-06 18:33
@mooreryan thank you for taking a look at this! 

@ekiefl I wouldn't mind trying to fix it, it would be a good exercise for me to practice using git. :)

**Comment by watsonar** [comment] 2020-08-06 18:57
@ekiefl it worked! 🎉 I submitted a pull request. I've never done this on my own before, so apologies if I messed something up.

**Comment by ekiefl** [comment] 2020-08-06 19:10
> @ekiefl it worked! 🎉 I submitted a pull request. I've never done this on my own before, so apologies if I messed something up.

This is great. I'll close the issue

**Closed** 2020-08-06 19:10 UTC
Labels: bug

**Comment by mooreryan** [comment] 2020-08-06 20:16
I added a couple more tests (#1483) to cover this bug...they all passed with @watsonar's `coord_cartesian` patch, so everything looks great!
