### ISSUE TITLE
[BUG] anvi-script-filter-hmm-hits-table is broken in the active branch

### ISSUE THREAD

**Issue by mschecht** [merenlab/anvio#1737] opened 2021-05-11 20:37 UTC
## Short description of the problem

`anvi-script-filter-hmm-hits-table` reports 1 failed line from `domtlblout` but the table looks fine.

## anvi'o version

```
$ anvi-self-test --version

Anvi'o .......................................: hope (v7-dev)

Profile database .............................: 35
Contigs database .............................: 20
Pan database .................................: 14
Genome data storage ..........................: 7
Auxiliary data storage .......................: 2
Structure database ...........................: 2
Metabolic modules database ...................: 2
tRNA-seq database ............................: 2```
```

## Detailed description of the issue

`anvi-script-filter-hmm-hits-table` seems to be running fine however it consistently reports that line 1 fails to be parsed. I took a look at the tmp file and it looks fine to me :/

## Files to reproduce

I can reproduce this with the Infant gut dataset by hard coding [parsers/base.py line 87](https://github.com/merenlab/anvio/blob/master/anvio/parsers/base.py#L87) to `return_failed_lines=False` and running debug
```bash
# Run hmmsearch and get domtblout
anvi-run-hmms -c CONTIGS.db                -I Bacteria_71                --hmmer-output-dir asdf                --just-do-it                --get-domtable-output ddd                --hmmer-program hmmsearch -T 10

# Run anvi-script-filter-hmm-hits-table 
anvi-script-filter-hmm-hits-table -c CONTIGS.db                                   --hmm-source Bacteria_71                                   --domtblout asdf/hmm.domtable                                   --query-coverage 0.8 --debug
HMM profiles .................................: 9 sources have been loaded: Bacteria_71 (71 genes, domain: bacteria), Archaea_76 (76 genes, domain: archaea), Ribosomal_RNA_23S (2 genes, domain: None), Ribosomal_RNA_28S (1 genes,
                                                domain: None), Ribosomal_RNA_5S (5 genes, domain: None), Ribosomal_RNA_16S (3 genes, domain: None), Ribosomal_RNA_12S (1 genes, domain: None), Protista_83 (83 genes, domain: eukarya),
                                                Ribosomal_RNA_18S (1 genes, domain: None)
Database Path ................................: CONTIGS.db
Domtblout Path ...............................: asdf/hmm.domtable
Num hits before filtering ....................: 685
Num hits after filtering .....................: 578
Num filtered .................................: 107

WARNING
===============================================
Previous entries for "Bacteria_71" is being removed from "hmm_hits_info,
hmm_hits, hmm_hits_in_splits, genes_in_contigs, gene_functions"


Traceback for debugging
================================================================================
  File "/Users/mschechter/github/anvio/anvio/parsers/base.py", line 87, in __init__
    ascii_only=True, return_failed_lines=False)
  File "/Users/mschechter/github/anvio/anvio/utils.py", line 3330, in get_TAB_delimited_file_as_dictionary
    "of the input matrix '%s' :/" % (column_mapping[i], line_fields[i], i + 1, file_path))
================================================================================
Traceback (most recent call last):
  File "/Users/mschechter/github/anvio/anvio/utils.py", line 3309, in get_TAB_delimited_file_as_dictionary
    updated_line_fields.append(column_mapping[i](line_fields[i]))
ValueError: invalid literal for int() with base 10: 'gene_callers_id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mschechter/github/anvio/anvio/parsers/base.py", line 87, in __init__
    ascii_only=True, return_failed_lines=False)
  File "/Users/mschechter/github/anvio/anvio/utils.py", line 3330, in get_TAB_delimited_file_as_dictionary
    "of the input matrix '%s' :/" % (column_mapping[i], line_fields[i], i + 1, file_path))

Traceback for debugging
================================================================================
================================================================================
anvio.errors.ConfigError:

Config Error: Mapping function '<class 'int'>' did not like the value 'gene_callers_id' in
              column number 1 of the input matrix
              '/var/folders/l4/c5v07vmj4jj9phh9lqm_hbz00000gq/T/hmm.table.fixed' :/



During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mschechter/github/anvio/sandbox/anvi-script-filter-hmm-hits-table", line 224, in <module>
    main(args)
  File "/Users/mschechter/github/anvio/anvio/terminal.py", line 866, in wrapper
    program_method(*args, **kwargs)
  File "/Users/mschechter/github/anvio/sandbox/anvi-script-filter-hmm-hits-table", line 203, in main
    p.process()
  File "/Users/mschechter/github/anvio/sandbox/anvi-script-filter-hmm-hits-table", line 92, in process
    self.get_hmm_hit_table(hmmsearch_tbl=x)
  File "/Users/mschechter/github/anvio/sandbox/anvi-script-filter-hmm-hits-table", line 184, in get_hmm_hit_table
    parser = parser_modules['search']['hmmer_table_output'](hmmsearch_tbl, alphabet=alphabet, context=context, program=hmm_program)
  File "/Users/mschechter/github/anvio/anvio/parsers/hmmer.py", line 585, in __init__
    Parser.__init__(self, self.program, [fixed_hmmer_table_txt], files_expected, files_structure)
  File "/Users/mschechter/github/anvio/anvio/parsers/base.py", line 89, in __init__
    raise StupidHMMError(f"{e}")

Traceback for debugging
================================================================================
================================================================================
anvio.errors.StupidHMMError:

Stupid HMM Error:   Config Error: Mapping function '<class 'int'>' did not like the
                  value 'gene_callers_id' in  column number 1 of the input matrix
                  '/var/folders/l4/c5v07vmj4jj9phh9lqm_hbz00000gq/T/hmm.table.fixed' :/
```

If I look at `/var/folders/l4/c5v07vmj4jj9phh9lqm_hbz00000gq/T/hmm.table.fixed` line 1 seems to be fine:
![image](https://user-images.githubusercontent.com/8404575/117880978-4f35ba80-b26e-11eb-8b8a-8db90a831eda.png)

**Comment by meren** [comment] 2021-07-13 19:28
Hey @mschecht,

I finally had a chance to look into this. Running the following two commands in `INFANT-GUT-TUTORIAL` (which are similar to yours with up-to-date flags), I couldn't reproduce this error:

```
anvi-run-hmms -c CONTIGS.db \
              -I Bacteria_71 \
              --hmmer-output-dir asdf \
              --just-do-it \
              --domain-hits-table \
              --hmmer-program hmmsearch \
              -T 10

anvi-script-filter-hmm-hits-table -c CONTIGS.db \
                                  --hmm-source Bacteria_71 \
                                  --domain-hits-table asdf/hmm.domtable \
                                  --query-coverage 0.8 \
                                  --debug
```

Did the problem fix itself?

**Comment by meren** [comment] 2021-07-29 18:44
Should we close this, @mschecht?

**Comment by mschecht** [comment] 2021-07-29 18:48
Sorry for the delay @meren. Yes let's close this, I cannot reproduce the error either.

**Closed** 2021-07-29 18:49 UTC
Labels: bug
