### ISSUE TITLE
--min-num-bins-gene-occurs doesn't work for external genomes in anvi-get-sequences-for-hmm-hits

### ISSUE THREAD

**Issue by ShaiberAlon** [merenlab/anvio#1060] opened 2018-12-05 20:12 UTC
When using `--min-num-bins-gene-occurs` in `anvi-get-sequences-for-hmm-hits` with external genomes then you get this message:

```
Config Error: OK. Well. This is awkward. You have like 1 bins, eh? And you are asking anvi'o
              to remove any that occurs in less than 5 bins. Do you see the problem here?
              Maybe it is time to take a break from work :(
```

They way I think it should work is:
1. replace `--min-num-bins-gene-occurs` to `--min-num-genomes-gene-occurs` (more compatible with the names `--external-genomes` and `--internal-genomes`
2. when this parameter is specified then the total number of internal + external genomes should be considered. For example if there are two internal genomes and one external genome in the analysis. And the hmm is in the external genome and also in ONE of the internal genomes. AND `--min-num-genomes-gene-occurs` is 2. Then anvi'o should be happy and give us the output sequences.

@meren, what do you think?

**Comment by meren** [comment] 2018-12-05 20:17
Both suggestions make sense.

For the (1), we need to make sure the parameter name change is reflected on any relevant web material.

For (2), would you like to do it or would you prefer me to do it? :)


Best,

**Comment by ShaiberAlon** [comment] 2018-12-05 20:34
I would prefer that you do t if you don't mind.
Especially because #1061 makes me worry that there are more hidden issues with this module.

**Comment by meren** [comment] 2018-12-05 20:36
I see. I am looking at it now.

**Comment by meren** [comment] 2018-12-05 20:53
Can you try again after cf874b8673160fd9709087076e1db2d36da8dde3? :)

**Comment by ShaiberAlon** [comment] 2018-12-05 23:22
This still doesn't work.

**Comment by meren** [comment] 2018-12-05 23:46
I wanted to see whether closing was going to fix it :(

**Comment by ShaiberAlon** [comment] 2018-12-05 23:53
You should open an issue with the GitHub people :-)

**Comment by meren** [comment] 2018-12-05 23:55
Brilliant.

**Comment by ShaiberAlon** [comment] 2018-12-06 14:57
Nope...

If you want to easily reproduce my issue, then checkout the branch `metapan-workflow`, and then run `./run_pangenomics_workflow_tests.sh` (in the anvio test folder).

**Comment by meren** [comment] 2019-04-10 21:51
I tried and couldn't reproduce this using the script `./run_pangenomics_workflow_tests.sh`. I assume it is somehow fixed :(

**Closed by meren** 2019-04-10 21:51 UTC
Labels: feature request
