### ISSUE TITLE
Transfer_RNAs HMM source yields gene with negative start position

### ISSUE THREAD

**Issue by ekiefl** [merenlab/anvio#1367] opened 2020-03-10 22:12 UTC
![image](https://user-images.githubusercontent.com/8688665/76364221-a51d7400-62f2-11ea-82c9-42180fb0d180.png)

Looking at this `genes_in_contigs` table, there is a gene predicted to have a start position that is negative. This breaks `anvi-profile`

It is worrying because to me it suggests such a shift may happen commonly, and that it is only caught in this particular instance, where the shift pushes the gene off the contig.

Tagging you @semiller10 

Until this is fixed, perhaps tRNA should not be run by default? What do you think @meren?

**Comment by ekiefl** [comment] 2020-03-10 23:28
Here is a minimal reproducible example. Save this fasta as `test.fa`:

```
>test
TCCCAATAGGATTCAAACCTATAACCTTTTGATCCGTAGTCAAATGCTCTATTCAGTTGAGCTATGGGACCAGTTCAGGA
CTTAGTCCTGTAACTTATTTAGTCTCTGCGTTAGCAGCACCTTCTTCTTTAAGAATCACGAGCTTCTTCTCCTTGATTCT
AGCCTTCTTACCAGAAAGTCCTCTGAGGTAGAAGATTCTTGCTCTACGTACGTGACCAACCTTGTTAACTTCGATAGATT
CGATAGATGGTGACTGGAATGGGAAAATTCTCTCAACACCTACACCGCCTGAAATCTTACGAACTGTGAAAGTCTTCGTG
AATGGTGATGATCCGCTGATCTGGATAACTACACCTCTAAACTTCTGAAGTCTTTCCTTGTCACCCTCTTTAATCTTGAG
GCTTACGGTGATTGTGTCACCTGCCTTGAATTTTGGATAACTTGCAGCTTTCTCGTTTGTAAAAGACTGCTCTACTAATT
TTATCAAATCCATTTCTAAATCACTTTTTAAGCGCAACGTTACTCAAATACTCAACGATTGTAAGAGGTTGCTTTGTTAA
TGGGATTGCAAAGGTACAACCTTTTTTTTAATCTGCAAGCTTTTTTAGAAATTTTCTTTCATTTTTTCGAAAAGATTTCG
ATCCTCGTTGCTGAGCACAGGTGTGAACGTGTCACTTGACCTCATGCCTTCGAGGGCACTCTTCTCGTTGCTCTTCAGCT
TCTTAGGTATCCAGACAAGGTATTTTACATATAGGTCTCCGGTGCCTGAACCATATCCTTTCACTGCAGGAAGTCCACGT
CCTCTCAGACGTACGATTGTTCCGGACTGTGTTCCAGGTTCTACCTTTATCTTATAGTTACCATCTAAGCAAGGTACTGA
AACTTCTCCTCCGAGGATAGCGTCCGTAACAGGTATTATCTTGGTATAGAACAGGTTCTTGCCCTCTCTCTTCAGTGATT
CGTGTGGAATCTCCTCGATAACGACGAGCAAGTCTCCGTTTATGCCGCCGGCTTTTGCTGAATGTCCTTCACCCTTTAGG
GTAAGCTGCATTCCGTCTTCCACGCCCGCAGGAATGTTTACCTTTACAGTAACTCTCTTTCTTACAAGTCCGCTACCGCC
GCAAGTGTGACATGGGTTCGTGACGATTTTTCCTTCACCGCCGCAACGTGAACAAGTTGTGTATGTTACCGTCTGTCCGA
AGATGCTGTTTGCCACTCTCTGTTCCTGGCCGGTGCCGTGGCATACCGGACAAGTCTTCACATCAGAAGCATTGACAGTA
CCCTTTCCGGCGCAGTCGGGGCATTTCTCATAGCGGTCGATGGTGACTTCCTTGGTCACGCCCTTGGCGATTTCTTCGAG
CGTCAGCCTTACGCGGGTACGGATGTCGCGTCCGCGCATTACTCTAGGCTGGGCCTGGCCGCGTTGTCCGCCGCCGAACC
CTCCAAAGCCGCCGAAGCCGGAAAATCCGCCGAATCCGCCACCTCCGAACAGGTCGTTCAGGATGTCGTTCAGGTTTCCG
AATCCGCCGCTGAAGTCAGGTCCCGGGTTTCCGCCCAAGCCGGCCTGTCCGAAACGGTCATATTTTGCACGTTTGTCAGG
GTCGCTCAGGACTTCATAAGCCTCAGATGCTTCCTTGAATTTCTCTTCTGCGGTTTTCTTCTCTTCGTCAGTTCCGTTTA
CCCACCTGTCAGGATGCCACTTGAGAGCCATCTTCTTGAAGGCTGACTTTATGTCATCCGCACTGGCGTTCTTATCTATG
CCGAGTACTTCGTAATAATCTCTTTTCTCTGCCATAATTTCCTCCTTCGGAATATCGATCTGCTATATTCCGACCACTAC
CTTAGCGTAGCGCAATATCTTGCCGTTGAACAGGTAACCTGTTTCCACGACATCGTATACCAATCCTTTTTTCTCTTTCT
CTGCTACTGGAACC
```

Then run 

```
rm CONTIGS.db; anvi-gen-contigs-database -f test.fa; anvi-run-hmms -c CONTIGS.db
```

Then open the CONTIGS.db and observe negative start value:

![image](https://user-images.githubusercontent.com/8688665/76368041-eca8fd80-62fc-11ea-8e2d-23fae082bce4.png)

**Comment by xvazquezc** [comment] 2020-03-10 23:55
It's a tRNAscan-SE thing, first time I see it though. I ran it outside anvi'o and gives the same output:
```
Sequence                tRNA    Bounds  tRNA    Anti    Intron Bounds   Inf           
Name            tRNA #  Begin   End     Type    Codon   Begin   End     Score   Note
--------        ------  -----   ------  ----    -----   -----   ----    ------  ------
test            1       68      -1      Arg     ACG     0       0       43.2    
```

**Comment by meren** [comment] 2020-03-11 00:03
One solution could be `IF START < 0: START = 0` for this case :/

> PS: technically not an HMM but CM ;)

Ssshh :p We are being sneaky here and using the HMM framework because it fits like a glove :p

**Comment by meren** [comment] 2020-03-11 00:04
Thanks for the reproducible example. I will take a quick look and see if the solution above could be applicable.

**Comment by meren** [comment] 2020-03-11 00:15
Using @ekiefl's test sequence, current `master`:

```
rm -rf CONTIGS.db; anvi-gen-contigs-database -f test.fa --quiet; anvi-scan-trnas -c CONTIGS.db --quiet; sqlite3 -header -column CONTIGS.db 'select * from genes_in_contigs where source="Transfer_RNAs";'

gene_callers_id  contig      start       stop        direction   partial     source         version
---------------  ----------  ----------  ----------  ----------  ----------  -------------  ----------
3                test        -2          68          r           1           Transfer_RNAs  unknown
```

After ea636528f45b794d8e39897ad064d4f4a90ad213:

```
rm -rf CONTIGS.db; anvi-gen-contigs-database -f test.fa --quiet; anvi-scan-trnas -c CONTIGS.db --quiet; sqlite3 -header -column CONTIGS.db 'select * from genes_in_contigs where source="Transfer_RNAs";'

gene_callers_id  contig      start       stop        direction   partial     source         version
---------------  ----------  ----------  ----------  ----------  ----------  -------------  ----------
3                test        0           68          r           1           Transfer_RNAs  unknown
```

Is it acceptable?

**Comment by ekiefl** [comment] 2020-03-11 01:50
It is to me.

**Comment by semiller10** [comment] 2020-03-11 02:07
When I run that contig with `tRNAscan-SE 2.0.5 (October 2019)` I get the following sensible output.

```
Sequence		      tRNA	Bounds	tRNA	Anti	Intron Bounds	 Inf
Name    	tRNA #	Begin	End 	  Type	Codon	Begin	End	     Score 	Note
--------	------	-----	------	----	-----	-----	----	   ------	------
test    	1	      68  	1   	  Arg	  ACG	  0	    0	       41.0
```

**Comment by xvazquezc** [comment] 2020-03-11 02:13
@semiller10 what options did you use? I ran the same and [I got it different](https://github.com/merenlab/anvio/issues/1367#issuecomment-597376054). I ran `tRNAscan-SE -G` which is how anvi'o runs it internally, if I'm not mistaken.
....
PS: I ran it without options and got the same, but in that way you run only the eukaryotic models

**Comment by semiller10** [comment] 2020-03-11 02:19
Ok, yes, with `-G`, it gives -1, with `-B` (bacterial) it gives 2, with `-O` (organellar), it gives 1.

**Comment by meren** [comment] 2020-03-11 18:12
Well. I think this solution is good enough for now given values change based on model used.

as soon as we hear back from @brymerr921 we can close this issue I think.

**Comment by meren** [comment] 2020-04-01 10:55
I consider it is addressed.

**Closed by meren** 2020-04-01 10:55 UTC
Labels: bug
