### ISSUE TITLE
[BUG] Oh no! anvi-compute-functional-enrichment switches un-adjusted and adjusted p-value columns

### ISSUE THREAD

**Issue by ivagljiva** [merenlab/anvio#1707] opened 2021-04-02 16:49 UTC
## Short description of the problem

The adjusted_q_value and unadjusted_p_value columns are switched in the output of `anvi-compute-functional-enrichment`. I think it only happens for module enrichment (ie not for pangenome or functions), but more testing is necessary to verify this.

Be careful with your module enrichment outputs, everyone!

## anvi'o version

v7

## Detailed description of the issue

The adjusted q value should never be smaller than the unadjusted p value, yet in some metabolism enrichment outputs, it is. Here is one example:
```
unadjusted_p_value	adjusted_q_value
(...)
0.42919529913288146	0.0481219220214391
0.548306045012894	0.06079369489786691
0.6325851203393026	0.06936742846517535
```

The columns are simply switched, and I need to fix this :)

**Comment by ivagljiva** [comment] 2021-04-21 18:22
## Further tests

I ran `anvi-compute-functional-enrichment` with all 3 input modes using the Enterrococcus genomes from the Infant Gut Tutorial dataset, and in all cases the p- and q- values were properly placed (there was no switch). For instance, here are the unique p/q value pairs from the modules enrichment output on this data:
```
$ cut -f 3,4 Enterococcus_enriched_modules.txt | uniq
unadjusted_p_value	adjusted_q_value
9.110979983090492e-4	0.006681385320933027
0.006024703126062904	0.03786956250668111
0.2505920458675303	1
0.2505920458675306	1
0.30305232927257136	1
0.3383343519015536	1
0.38691631424217526	1
1	1
```
As you can see, in every pair, p <= q. The same thing happened with pangenome enrichment and external genome groups enrichment.

This means that we have a scary non-deterministic error on our hands. It is happening with some datasets but not with others. 😨 

I then tested on a different set of input data. When I ran using 'groups of internal genomes' input, the top of the file looked fine with p < q, but at some point it switched to p > q! Here is the output, with the switch location annotated:
```
unadjusted_p_value	adjusted_q_value
4.2621303835548e-12	1.0713384139032872e-10
4.2621303835548e-12	1.0713384139032872e-10
4.2621303835548e-12	1.0713384139032872e-10
(....) (....)
0.04423905113962197	0.04489450941282124
0.044239051139621816	0.04489450941282124
## -----> SWITCH HAPPENED, now p > q <-------
0.045873294679985264	0.04516816777546974
0.04587329467998565	0.04516816777546974
0.04678944013277028	0.04516816777546974
(...) (...)
0.892637298317399	0.31197189580879797
0.8949876848111705	0.31197189580879797
0.897190172983134	0.31197189580879797
1	0.33757318483595267
```
In fact, the same thing occurred for the modules enrichment on this data. It started out fine with p < q and then by the end of the file turned into p > q:
```
unadjusted_p_value	adjusted_q_value
4.262130383554765e-12	6.000767418640703e-11
1.541407915625281e-10	1.6276420885565241e-9
1.5423514589508432e-9	1.3029107347831912e-8
4.758602390969618e-9	3.349881821562219e-8
(....) (....)
0.8326467702015404	0.20447191897902958
0.8845098508752093	0.21595232738382625
0.8949876848111705	0.21725467425713105
1	0.23729102684864584
```
WHAT IS THIS SORCERY. 😢

**Comment by ivagljiva** [comment] 2021-04-21 19:35
I decided to run through the R script line by line on my example dataset to see where these values are coming from. So I ran `anvi-compute-functional-enrichment` (internal genomes input mode) with the `--debug` flag to get an input file for `anvi-script-enrichment-stats`, opened up Rstudio, and basically ran the commands from `anvi-script-enrichment-stats` one at a time on the input file.

The following line gets you a dataframe of p-values and enrichment scores for each function:
```
# get the p-values & enrichment_scores
pvalues_df <- w_models %>%
  transmute(accession,
            "unadjusted_p_value" = map_dbl(model, get_unadjusted_p_value),
            "enrichment_score" = map_dbl(model, get_enrichment_score))
```
After this line, there is a part where the script generates the q-values and immediately puts all the data together into a dataframe for the output file. Instead of this, I took just the part for generating q-values and put it into it's own df:
```
max_lambda <- min(0.95, max(pvalues_df$unadjusted_p_value, na.rm=T))
qvals <- pvalues_df %>%
    mutate("adjusted_q_value" = qvalue::qvalue(unadjusted_p_value,
                                               lambda = seq(0.05, max_lambda, 0.05))$qvalues)
```
And this is what `qvals` looks like:
![image](https://user-images.githubusercontent.com/10360586/115609709-7f142280-a2ad-11eb-88e1-c02e24650898.png)

So actually, here already we have p > q for some of the functions. The q-values that are being returned _by the qvalue package_ are in many cases less than the value in the `unadjusted_p_value` column. 

So, now I am wondering if I am just mis-understanding something here :( 
My knowledge of statistics is clearly insufficient. We must turn to the expert :)

**Comment by ivagljiva** [comment] 2021-04-21 19:35
@adw96, what could cause adjusted q-value to be less than unadjusted p-value? Is this actually normal, or do we really have a bug here? Thank so much for your advice!

**Comment by adw96** [comment] 2021-04-22 06:55
I'll have to think about this some more, @ivagljiva -- but I'm optimistic that this is not a bug. Maybe I'm overtired, but my intuition is that there are probably a lot of p-values of 1 in this dataset, and they eat up the high q-values, pushing down the remainder. Are you able to send me the qvals tibble from above as a csv or RDS to help me confirm? (sorry, I'm sure I could reproduce this example but this would save me ages 😊) 🙏

**Comment by adw96** [comment] 2021-04-22 07:01
Also, just given what q-values are trying to do (distinguish true signals from signals generated under a background noise/null), it makes sense to me that the smallest p-values will have q-values smaller than their corresponding p-values, and the largest p-values will have q-values larger than their corresponding p-values. Essentially a good q-value procedure (slash well-behaved dataset) should help us further highlight real signals and further ignore all the nothings.

As long as the ordering is preserved (p from COG i < p from COG i' => q from COG i < q from COG i') I'm not going to get too alarmed. 

I believe I have convinced myself that this is not a problem, but I'm happy to look into it and confirm, @ivagljiva !

**Comment by ivagljiva** [comment] 2021-04-22 16:13
@adw96, I cannot tell you how relieved I am to hear that! I'm so glad it's probably my ignorance and not a bug after all. 😅 

I would really appreciate it if you could confirm it. I've attached the CSV with the qvalue tibble:
[qvals.csv](https://github.com/merenlab/anvio/files/6359718/qvals.csv)

I can also give you the original input data for the script that these values are coming from, just let me know! Thank you so much!!

**Comment by adw96** [comment] 2021-04-30 12:03
Yep, confirming this is normal behaviour. In the example dataset in the `qvalue` package p-values close to 1 get assigned q-values ~0.6:

```
library(qvalue)
library(tidyverse)
data(hedenfalk)
plot(hedenfalk$p, qvalue(p = hedenfalk$p)$qvalues)
abline(0,1)
```

I'll close this issue but feel free to reopen if feel I haven't addressed your concerns, @ivagljiva 🍄 

😸

**Closed by adw96** 2021-04-30 12:03 UTC
Labels: bug, metabolism / modules database

**Comment by meren** [comment] 2021-04-30 12:32
You're the best, @adw96! Thank you!

**Comment by ivagljiva** [comment] 2021-04-30 14:41
Thank you so much @adw96!! 👑 🐝
