### ISSUE TITLE
anvi-export-locus suggestions

### ISSUE THREAD

**Issue by meren** [merenlab/anvio#611] opened 2017-10-19 13:34 UTC
I should have done this under #610, but I failed, so here are some suggestions :)

First of all, thank you for this, Alon. I think this will help everyone to do more systematical searches for genomic loci.

* How would you feel about changing the program name from `anvi-export-gene-block` to `anvi-export-locus`? according to a random dictionary online locus means "the effective or perceived location of something abstract". I think it fits very nice. Block is a keyword used for search algorithms, and I think it doesn't fit very well here.

* How would you feel about changing `-b` / `--block-size` parameter to `-n` / `--num-genes`? I feel like it would have been much more intuitive.

* Would you mind adding an 'example' at an appropriate place in the `run_all_tests.sh` file? So at least there would be one example somewhere we run often so if a change somewhere else in the codebase breaks things in this program we would have a way to quickly identify it?

* Finally, HMM is an acronym, so except for flags and parameters, we should always write it as 'HMM' and not 'hmm' (i.e., in the the help menu) :)

By the way, what happens when a gene is found, but the contig is shorter than `-b`? :)

Thanks!

**Comment by ShaiberAlon** [comment] 2017-10-20 14:22
```* How would you feel about changing the program name from `anvi-export-gene-block` to `anvi-export-locus`? according to a random dictionary online locus means "the effective or perceived location of something abstract". I think it fits very nice. Block is a keyword used for search algorithms, and I think it doesn't fit very well here.```
I accept!

```* How would you feel about changing `-b` / `--block-size` parameter to `-n` / `--num-genes`? I feel like it would have been much more intuitive.```
Done!

```* Would you mind adding an 'example' at an appropriate place in the `run_all_tests.sh` file? So at least there would be one example somewhere we run often so if a change somewhere else in the codebase breaks things in this program we would have a way to quickly identify it?```
Done! Added two examples (one for HMM and one for functional annotations search)

```* Finally, HMM is an acronym, so except for flags and parameters, we should always write it as 'HMM' and not 'hmm' (i.e., in the the help menu) :)```
Fixed! Thank you!

```By the way, what happens when a gene is found, but the contig is shorter than `-b`? :)```
Then I return the sequence until the end of the contig. And the same if you ask for genes preceding the gene and hit the beginning of the contig, then in that case the sequence starts from the start of the contig. I added a note about this to the help menu.

Thank you for giving this a look!

**Comment by meren** [comment] 2017-10-21 08:06
Thanks for these changes, Alon.

I thought you'd like to know that this line produces an output file with identical sequences:

https://github.com/merenlab/anvio/commit/f35ea6593df39ab5be68e9240fa82d97e130685b#diff-bcf3e47075e6daafc409adc7a3c0787aR83

It highlights an interesting problem: sometimes the same gene can be annotated with multiple functions (by the same or different functional annotation sources) that may share the keyword of interest. Maybe we should only work with unique gene caller ids once the hits for functions/HMMs are gathered.

Also, as another 2 cents I have this to share: the deflines of resulting FASTA files could contain a bit more information so the user is not lost when they look at the results a week later :)

The current defline looks like this:

```
>0__204_10M_MERGED.PERFECT.gz.keep_contig_878__positions_0_27450__genes_0_22
```

It could have looked like this:

```
>CONTIGSDBNAME_ENTRYID target:TARGET|query:QUERY|hit_contig:CONTIGNAME|hit_gene_callers_id:GENECALLERSID|locus:LOCUS|positions:POSITIONS|premature:PREMATURE
```

where,

* `CONTIGSDBNAME`: the `contigs_db.a_meta['project_name']`
* `ENTRYID`: unique numeric entry id.
* `TARGET`: HMMs or functions (or maybe even gene callers id (if someone wants to take a locus with a known gene callers id, for instance)
* `CONTIGNAME`: contig name the locus is found
* `GENECALLERSID`: gene callers id of the hit
* `LOCUS`: 0,22 (or whatever matches)
* `POSITIONS`: 0:27450 (or whatever matches)
* `PREMATURE`: False or True depending on whether both ends of the LOCUS were within the contig, of whether it ended prematurely (the user asks for 10 genes, contig has only 8 after the hit, etc).


Best,

**Comment by ShaiberAlon** [comment] 2017-10-21 11:49
I like the suggestion regardimg the deflines.

I'm not sure I understand the other issue that you are raising. But let me
try: you say that multiple sources could annotate the same gene, and that
it would prodice redundant outputs?

Since after I search, I get a list of gene_callers_id's then this issue
should be solved by making sure that list is unique.

Another thing I thought of is that I don't think there's a reason to
separate searching HMMs and searching functions, unless the user requests.
Meaning that the default should search through all functional annotation
and all HMM sources and then use a unique collection of gene ids.

Let me know what you think.

On Oct 21, 2017 3:06 AM, "A. Murat Eren" <notifications@github.com> wrote:

Thanks for these changes, Alon.

I thought you'd like to know that this line produces an output file with
identical sequences:

f35ea65#diff-bcf3e47075e6daafc409adc7a3c0787aR83
<https://github.com/merenlab/anvio/commit/f35ea6593df39ab5be68e9240fa82d97e130685b#diff-bcf3e47075e6daafc409adc7a3c0787aR83>

It highlights an interesting problem: sometimes the same gene can be
annotated with multiple functions (by the same or different functional
annotation sources) that may share the keyword of interest. Maybe we should
only work with unique gene caller ids once the hits for functions/HMMs are
gathered.

Also, as another 2 cents I have this to share: the deflines of resulting
FASTA files could contain a bit more information so the user is not lost
when they look at the results a week later :)

The current defline looks like this:

>0__204_10M_MERGED.PERFECT.gz.keep_contig_878__positions_0_27450__genes_0_22

It could have looked like this:

>CONTIGSDBNAME_ENTRYID target:TARGET|query:QUERY|hit_contig:CONTIGNAME|hit_gene_callers_id:GENECALLERSID|locus:LOCUS|positions:POSITIONS|premature:PREMATURE

where,

   - CONTIGSDBNAME: the contigs_db.a_meta['project_name']
   - ENTRYID: unique numeric entry id.
   - TARGET: HMMs or functions (or maybe even gene callers id (if someone
   wants to take a locus with a known gene callers id, for instance)
   - CONTIGNAME: contig name the locus is found
   - GENECALLERSID: gene callers id of the hit
   - LOCUS: 0,22 (or whatever matches)
   - POSITIONS: 0:27450 (or whatever matches)
   - PREMATURE: False or True depending on whether both ends of the LOCUS
   were within the contig, of whether it ended prematurely (the user asks for
   10 genes, contig has only 8 after the hit, etc).

Best,

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/merenlab/anvio/issues/611#issuecomment-338374041>, or mute
the thread

**Comment by meren** [comment] 2017-10-21 12:06
> you say that multiple sources could annotate the same gene, and that
> it would prodice redundant outputs?

Yes, exactly :)

> Since after I search, I get a list of gene_callers_id's then this issue
> should be solved by making sure that list is unique.

Correct!

> Another thing I thought of is that I don't think there's a reason to
> separate searching HMMs and searching functions, unless the user requests.

An excellent idea. I agree!

**Comment by ShaiberAlon** [comment] 2017-10-21 12:33
Great, so before I make the changes, I wanted to see we are on the same
page:

Default: search all funational annotations sources and HMM sources.

Otherwise, you need to supply a list of sources.

We can either have one flag --use-sources or two: --hmm-sources,
--annotation-sources.

If we use the flag --use-sources, then you can supply a list of
comma-separated sources, and it could include both functional annotation
and HMM sources. The problem is that if you have an HMM source and a
functional annotation source with identical name then this will be the
first and only time that anvio will inform you that it doesn't like that.

If we use two flags, then if the user supplies only one of --hmm-sources or
--annotation-sources then the other is an empty list.

I prefer the two flag solution.

What do you think?

**Comment by meren** [comment] 2017-10-21 13:29
Great. Just to have a simpler language, how about these flags:

An optional `--sources` parameter accepts comma-separated list of sources to be searched. Each source must match whatever sources the program considers (in our case HMMs and functions).

Two mutually exclusive optional flags `--search-hmms` and `--search-functions` limit the search space, in this case, if there also is a `--sources` parameter, then the program makes sure the desired search space and the sources have perfect match (of course, at some point the user will be like "what sources are available to me?" and will look for a `--list-sources` flag .. but maybe the best solution for that is to implement a program like `anvi-show` that shows everything there is to know about an anvi'o database).

One of the last parameters could be `--gene-callers-id` to define a specific gene (or a list of comma-separated gene ids?) to define the 'hit'.

Finally, these are all very useful, but also keep in mind that we shouldn't over-engineer this :) All it takes is two perfectionists to ruin the world.

**Comment by ShaiberAlon** [comment] 2017-10-21 14:45
I agree! I don't want to spend more time on this small script... I will do these soon, and give this script a rest :-)

**Comment by meren** [comment] 2017-10-21 15:05
Just a tiny note, this program has some parallels to `anvi-get-seqeunces-for-hmm-hits`, which started as a toy program, and now it is one of the most powerful secret weapons of anvi'o. I just wanted to mention in case you would like to take a look at its code for inspiration (if there is any) :)

**Comment by meren** [comment] 2018-01-02 23:35
Should we close this? Should this be one of the cools things we now have in our release notes?

We need to write tiny tutorials for these. Otherwise they get buried deep, and no one uses them.

Suggestions most welcome :)

**Comment by ShaiberAlon** [comment] 2018-01-03 01:21
I think we should include this in `v4`, but I think we shouldn't close it yet. I was planning to implement the option to choose functional annotation sources (right now I allow to choose hmm sources), but `search_splits_for_gene_functions` (in `ContigsSuperclass`) doesn't allow to specify the sources. I started a branch in which I was working on adding it, but I didn't even make one commit (but I do have one patch stashed there hehe :-) ). If you feel this is not important then we can stop here, and just close this issue. I will commit my stash (even though I usually try to only commit things that seem to work, and this is definitely just a work in progress), and publish my branch and you can either ignore it or give it a look.

There is also the `--gene-callers-id` option you mentioned [here](search_splits_for_gene_functions), that I didn't get the chance to implement.

**Comment by ShaiberAlon** [comment] 2018-01-03 01:26
Ok, so I didn't commit my stashed changes because unsurprisingly there were some conflicts in `dbops`, and I don't have time right now to deal with that. Sorry.

**Comment by meren** [comment] 2018-01-03 02:40
No worries! I just included this in `v4` milestone.

**Comment by ShaiberAlon** [comment] 2018-01-03 04:17
Also, I would be happy to write a small tutorial for this. You once mentioned the option of running the website locally. I think that would help me with writing the tutorial, it would be great if you or ozcan could show me how to do that.

**Comment by meren** [comment] 2018-01-03 04:37
Either @ozcan or I can help you with that for sure :)

**Comment by ShaiberAlon** [comment] 2018-02-03 21:21
So I decided to only implement the option for searching gene caller ids, and not implement the option to choose functional annotation sources (so you can still search functions, but it will always search all available functional annotation sources). If people will complain then we can do it for the next version (unless someone else feels like doing it... :-) ).

**Closed by ShaiberAlon** 2018-02-03 21:21 UTC
Labels: enhancement
