### ISSUE TITLE
Anvio functional annotations problems

### ISSUE THREAD

**Issue by pbravakos** [merenlab/anvio#999] opened 2018-10-02 09:27 UTC
PAnvi'o version ...............................: margaret (v5.1)
Profile DB version ...........................: 29
Contigs DB version ...........................: 12
Pan DB version ...............................: 12
Genome data storage version ..................: 6
Auxiliary data storage version ...............: 2
Structure DB version .........................: 1

Hello, I am using Debian 9 to run anvio commands on a server and Ubuntu 18.04 to run anvi-interactive on a personal computer. 
I have followed the metagenomics tutorial workflow and have imported interpro annotations. What i notice is that when i search for a term in search functions i get a different result about the unique gene calls on the terminal and on the anvio running on the browser.  Moreover, in the anvio interface on the browser i get multiple hits of the same result e.g. the same gene caller and the same source with the same accession are repeated multiple times for some of the results, which is confusing. Finally when i import some functions with the anvi-import-functions I notice that the results i get from the "Show results down bellow" option and the actual annotations when i inspect the split gene calls are sometimes different.
Thanks 
Panos

**Comment by meren** [comment] 2018-10-02 09:30
Would you mind sharing your contigs database with function calls and exact command lines you use and results you get? I am a bit confused about how to reproduce this as I have not been having such problems :)

**Comment by pbravakos** [comment] 2018-10-02 09:34
Yes of course. Where should i upload the contigs database? It is about 16MB.

**Comment by meren** [comment] 2018-10-02 09:42
The best would be to upload it in Dropbox, and share a download link publicly or privately through e-mail (if there is sensitive information).

Thank you very much!

**Comment by pbravakos** [comment] 2018-10-02 09:46
Sensitive no but because it is unpublished i would prefer to share it by email.
Panos

**Comment by meren** [comment] 2018-10-02 09:49
I see. Please feel free to send it to a.murat.eren@gmail.com and ozcanesen@gmail.com, and please consider sending a comment here for tested instructions so we can reproduce your problem.

**Comment by pbravakos** [comment] 2018-10-02 10:15
I hope you have access to the dropbox folder. 
For example you can search for "resistance" to check the multiple outputs.
Also from the same results Gene caller id: 3441 shows different information for the Interpro source in the search results (Accession: IPR004812 Annotation: Drug resistance transporter Bcr/CmlA subfamily) and different in the gene call info from the "Scaffold_5_length_514556_pilon_split_00022 detailed" where both the interpro accession and annotation is "none".

**Comment by meren** [comment] 2018-10-15 11:15
Hi @pbravakos, I am very sorry we still haven't been able to get back to this. Thank you very much for sending the data to reproduce this issue and your patience with us. I hope we are going to be able to get back to this rather soon.

**Comment by ozcan** [comment] 2018-10-16 17:08
Hi @pbravakos,
I am looking into this issue today, it seems `interproscan` sometimes generates multiple annotations for same entry with different start/end values.

Example:
```
4	610322b29a53a7c1eccdd3af0e0cb5da	1126	ProSiteProfiles	PS50975	ATP-grasp fold profile.	681	881	44.146	T	09-11-2015
4	610322b29a53a7c1eccdd3af0e0cb5da	1126	ProSiteProfiles	PS50975	ATP-grasp fold profile.	133	328	50.073	T	09-11-2015
```
I am going to modify parser to collapse duplicates.

**Comment by pbravakos** [comment] 2018-10-16 17:31
Hi @ozcan,
Ok. Certainly this will get things less cluttered, although some information will be lost.
The problem i think is that interpro searches different databases which sometimes do not agree on the start and end points or the annotation of the regions. Hope you will be able to find an algorithm, which will result in a consistency on what kind of information is thrown away each time.

**Comment by meren** [comment] 2018-10-16 17:48
@pbravakos, @ozcan's current solution aims to collapse only identical functional annotations that are assigned to the same gene call. since anvi'o does not keep track of which domains/regions in the gene were affiliated with the assigned function, no information will be lost, in fact.

**Comment by meren** [comment] 2018-10-16 18:00
The most likely explanation is the presence of multiple amino acid sequences in the source database that align different parts of the gene (i.e., different start-stop positions) yet resolve to the same function name.

**Comment by pbravakos** [comment] 2018-10-16 18:36
Ok thanks for the explanation. 
I just realized that these are exact duplicates, except for the start and end positions. 
Multitasking makes me nonfunctional. Sorry for bothering you. 
Anvio is an amazing program and really useful for my work, and it is  nice it is actively maintained.

**Closed** 2019-04-20 04:29 UTC
