### ISSUE TITLE
anvo-export-locus exports overlapping things (in v5.5)

### ISSUE THREAD

**Issue by ShaiberAlon** [merenlab/anvio#1228] opened 2019-09-09 16:03 UTC
Notice: I only tested this behavior with `v5.5` and I don't know if this was modified in `master`, but I assume it wasn't.

When a contig includes two hits for the search term, and the two hits are close enough (according to exporting length requested by the user) then a separate output would be created for each of these. On one hand, that makes sense, but I am not sure that it is a favorable behavior.

For example let's assume we search for some function, for example: `SOME_FUNCTION`. And let's say that `contig_01` has gene_caller_id `5`, and `8` annotated with `SOME_FUNCTION`, and that the user specified `--num-genes 4,4`, then currently the output would include two things:
1. one output with genes between 1 and 9
2. second output with genes between 4 and 12

The problem with the current behavior is the redundancy between the outputs.

I think that it is more useful if instead, there is a single output with genes between 1 and 12. Or at the minimum there should be a flag to choose which behavior the user prefers.

@SchmidAbby , @meren , @mschecht , what do you think?

@mschecht , I know you are currently working on this, so maybe you would like to consider this enhancement.

**Comment by SchmidAbby** [comment] 2019-09-11 21:56
I think it is probably best to leave the option to the user and add a flag

**Comment by meren** [comment] 2019-10-02 18:51
@mschecht?

**Comment by mschecht** [comment] 2019-10-02 21:05
@ShaiberAlon thanks for bringing up this point. After reflecting on it, I agree with @SchmidAbby in that I don't think we should assume the user's target locus and thus modify the output. I will add a warning message that will appear in stdout stating there is overlap between the extracted loci so that the user will be aware. 

I want to point out that this issue will only affect `default-mode`not `--flank-mode` because `--flank-mode` currently can only cut out one locus at a time from a genome.

**Comment by ShaiberAlon** [comment] 2019-10-03 02:44
@mschecht , while I think a warning is appropriate, I wasn't suggesting to assume what the user wants, I said:
>at the minimum there should be a flag to choose which behavior the user prefers.

And @SchmidAbby said:
>I think it is probably best to leave the option to the user and add a flag

You don't see the value of such a flag that would choose between the two alternative behaviors? If not, then feel free to just add the warning and close this issue.

**Comment by mschecht** [comment] 2019-10-03 03:02
@ShaiberAlon thank you for the clarification, I misinterpreted "flag" as "warning" in your and @SchmidAbby's comments. I'll be sure to read closer next time. 

Yes I do not think a flag designating between the two behaviors is  a necessary feature at the moment and am currently adding a detailed warning message to address it. Once I commit Ill close the issue.

**Comment by mschecht** [comment] 2019-10-10 16:32
Here is a reproducible example for providing a warning message to the user when exported loci are overlapping. Please un-comment out the code block [here](https://github.com/merenlab/anvio/blob/master/anvio/splitter.py#L872-L903) and give it a try. I discussed this with @meren and we will add this in a future version of anvio depending on user needs.

step 1) Run the run_all_tests.sh until contigs DBs have been annotated
```
cd anvio/anvio/tests/

./run_all_tests.sh
```

Step 2) Then run this anvio command for anvi-export-locus
```
anvi-export-locus -c sandbox/test-output/CONTIGS.db \
                  -O sandbox/test-output/exported_locus_from_functions \
                  -n 1,1 \
                  -s NusB,'Glutamine amidotransferase class-I' \
                  --overwrite-output-destinations
```

The output should give you a warning for overlapping loci

**Closed** 2020-04-01 11:14 UTC
Labels: contigs database, enhancement
