### ISSUE TITLE
[BUG] `anvi-script-gen-function-matrix-across-genomes` does not know option `--skip-checking-genome-hashes`

### ISSUE THREAD

**Issue by Louis-MG** [merenlab/anvio#2343] opened 2024-09-19 22:58 UTC
## Short description of the problem

Help message indicates that I should use an option that is then refused as unknown.

## anvi'o version

dev, installed using the documentation. Updated just sept.19 18h54 (canadian time).

## Detailed description of the issue

I want to duplicate contigsDB to compute functional enrichment accross genomes. I want to ignore the hashes of the db to force anvio. I believe you just forgot to implement it :D .

```
(anvio-dev) me@vls142:/mnt/scratch/LM/pangenomic$ anvi-script-gen-function-matrix-across-genomes -e external_genomes.txt -G groups.txt --annotation-source Uniref90  --output-file-prefix functional_enrichment_all --skip-checking-genome-hashes

Groups found and parsed ......................: dry, moist, sebaceous, toenail
                                                                                                                                                                                              

Config Error: While working on your external genomes, anvi'o realized that genome            
              GCF_000069245_1_ASM6924v1_genomic_contigs_db_db and                            
              GCF_000069245_1_ASM6924v1_genomic_contigs_db_db2 seem to have the same hash. If
              you are aware of this and/or if you would like anvi'o to not check genome      
              hashes, please use the flag `--skip-checking-genome-hashes`.  
```

**Comment by meren** [comment] 2024-09-21 12:09
Hey @Louis-MG,

I don't think this program actually cares about the duplicate hashes. I just tested it with copy-pasta genomes without using `--skip-checking-genome-hashes`, it worked fine :)

``` bash
$ anvi-script-gen-function-matrix-across-genomes -e external-genomes.txt \
                                                 -G groups.txt \
                                                 --annotation-source KOfam \
                                                 --output-file-prefix functional_enrichment_all
Groups found and parsed ......................: E_faecali, E_faecium

WARNING
===============================================
Just FYI, for any gene call with multiple functional annotations from the same
source in a given genome, anvi'o only kept the annotation with the BEST e-value.
Keep this in mind when interpreting the output of this program.

Number of KOfam functions found across 2 groups : 1,545
Number of KOfam functions associated with all groups and SKIPPED : 1,113
Number of KOfam functions in final occurrence table : 432

CITATION
===============================================
This program will compute enrichment scores using an R script developed by Amy
Willis. You can find more information about it in the following paper: Shaiber,
Willis et al (https://doi.org/10.1186/s13059-020-02195-w). When you publish your
findings, please do not forget to properly credit this work. :)


AMY's ENRICHMENT ANALYSIS 🚀
===============================================
Functional occurrence stats input file path:  : /var/folders/gw/5mdblzs94gsb1ss44llgl3_h0000gn/T/tmp4wy4yzrb/FUNC_OCCURENCE_STATS.txt
Functional enrichment output file path:  .....: /Users/meren/Downloads/INFANT-GUT-TUTORIAL/additional-files/pangenomics/functional_enrichment_all-FUNCTIONAL-ENRICHMENT.txt
Temporary log file (use `--debug` to keep):  .: /var/folders/gw/5mdblzs94gsb1ss44llgl3_h0000gn/T/tmpk3lz5hky


Functions across genomes (frequency) .........: /Users/meren/Downloads/INFANT-GUT-TUTORIAL/additional-files/pangenomics/functional_enrichment_all-FREQUENCY.txt
Functions across genomes (presence/absence) ..: /Users/meren/Downloads/INFANT-GUT-TUTORIAL/additional-files/pangenomics/functional_enrichment_all-PRESENCE-ABSENCE.txt
```

Only when I had literally identical genomes in two groups, anvi'o complained:

```bash
Groups found and parsed ......................: E_faecali, E_faecium

WARNING
===============================================
In an ideal world, each group would describe at least two layer names. It is not
the case for these groups: E_faecali, E_faecium. That is OK and anvi'o will
continue with this analysis, but if something goes wrong with your stats or
whatever, you will remember this moment and go like, "Hmm. That's why my
adjusted q-values are like one point zero 🤔".


WARNING
===============================================
Just FYI, for any gene call with multiple functional annotations from the same
source in a given genome, anvi'o only kept the annotation with the BEST e-value.
Keep this in mind when interpreting the output of this program.

Number of KOfam functions found across 2 groups : 1,246
Number of KOfam functions associated with all groups and SKIPPED : 1,246
Number of KOfam functions in final occurrence table : 0


Config Error: Something weird is happening here :( It seems every single function across your
              genomes is associated with all groups you have defined. There is nothing much
              anvi'o can work with here. If you think this is a mistake, please let us know.
```

I'm having hard time reproducing this :(

Can you explain EXACTLY how you ended up here? Perhaps you can send us the external genomes file you have?

**Comment by Louis-MG** [comment] 2024-09-23 00:24
Some of my species belong to several groups. For reasons we decided to duplicate the contig databases using links to have species in both groups.
```
#contains the contigs.db
cp -rl /path/to/species/folder/
```
. External genomes file uploaded. [external_genomes.txt](https://github.com/user-attachments/files/17091759/external_genomes.txt)
I tested anvio-8 and I still get the hashes check !

**Comment by meren** [comment] 2024-09-23 06:22
Very bizarre. I will do a more thorough investigation of this and come back to you hopefully soon, @Louis-MG. Although it will likely take a few days :( I'm very sorry for this.

**Comment by meren** [comment] 2024-10-11 11:21
Hey @Louis-MG,

My efforts to reproduce this failed. So I have no way of testing this since it is working for me. But maybe you can tar.gz the directory you're working with along with a README.txt file with the command you would like me to run in it to get the error.

If I can get the error you're getting, perhaps I can go from there.

Please send me a private email with a Dropbox download link.

**Comment by Louis-MG** [comment] 2024-10-11 15:54
@meren Done !

**Comment by meren** [comment] 2024-10-12 13:20
Hi @Louis-MG,

Thank you very much for the test data. I was able to reproduce your error, and fixed the codebase to allow the use of the parameter `--skip-checking-genome-hashes` with the program `anvi-script-gen-function-matrix-across-genomes`. I was able to successfully run the command on your test dataset, and I got this output, which will show you that there is another problem occurring now:

```
>>> anvi-script-gen-function-matrix-across-genomes -e external_genomes.txt -G groups.txt --annotation-source Uniref90  --output-file-prefix functional_enrichment_all  --skip-checking-genome-hashes
Groups found and parsed ......................: dry, sebaceous

WARNING
===============================================
While processing internal and/or external genomes files you have provided,
anvi'o found genomes with identical hashes (which means they were practically
identical to each other). But since you have instructed anvi'o to ignore that it
is now continuing with the flow (even though 0 hashes for your internal genomes
and 101) hashes for your external genomes appeared more than once). See below
the genome names with identical hashes:

External genomes with hash hashe1d049df ......: GCF_000144005_1_ASM14400v1_genomic_contigs_db_db3, GCF_000144005_1_ASM14400v1_genomic_contigs_db_db
External genomes with hash hash24395325 ......: GCF_000144025_1_ASM14402v1_genomic_contigs_db_db3, GCF_000144025_1_ASM14402v1_genomic_contigs_db_db
(...)


WARNING
===============================================
Just FYI, for any gene call with multiple functional annotations from the same
source in a given genome, anvi'o only kept the annotation with the BEST e-value.
Keep this in mind when interpreting the output of this program.

Number of Uniref90 functions found across 2 groups : 2,196
Number of Uniref90 functions associated with all groups and SKIPPED : 2,196
Number of Uniref90 functions in final occurrence table : 0


Config Error: Something weird is happening here :( It seems every single function across your
              genomes is associated with all groups you have defined. There is nothing much
              anvi'o can work with here. If you think this is a mistake, please let us know.
```

Indeed, every single genome occurred once in each group. I am hoping that this is no surprise to you, and the dataset you sent me is not the actual one you're using for your analyses :)

Apologies for the delay in responding to this, thanks for the test dataset, and I hope everything else goes smoothly after this.

I'm closing the issue now since the bug mentioned in the title is now fixed. But please open another issue if something else comes up.

**Closed by meren** 2024-10-12 13:20 UTC
