### ISSUE TITLE
key error when using --list-hmm-sources for external genomes

### ISSUE THREAD

**Issue by ShaiberAlon** [merenlab/anvio#821] opened 2018-04-27 20:49 UTC
When running:

```
anvi-get-sequences-for-hmm-hits --external-genomes external-contigs.txt --list-hmm-sources
```

I get:

```

HMM SOURCES COMMON TO ALL 113 GENOMES
===============================================
Traceback (most recent call last):
  File "/groups/merenlab/virtual-envs/anvio-master/anvio/bin/anvi-get-sequences-for-hmm-hits", line 280, in <module>
    main(args)
  File "/groups/merenlab/virtual-envs/anvio-master/anvio/bin/anvi-get-sequences-for-hmm-hits", line 101, in main
    s = hmmopswrapper.SequencesForHMMHitsWrapperForMultipleContigs(args, hmm_sources)
  File "/groups/merenlab/virtual-envs/anvio-master/anvio/anvio/hmmopswrapper.py", line 33, in __init__
    self.load_genomes_descriptions(skip_functions=True, init=False)
  File "/groups/merenlab/virtual-envs/anvio-master/anvio/anvio/genomedescriptions.py", line 200, in load_genomes_descriptions
    self.sanity_check()
  File "/groups/merenlab/virtual-envs/anvio-master/anvio/anvio/genomedescriptions.py", line 404, in sanity_check
    self.list_HMM_info_and_quit()
  File "/groups/merenlab/virtual-envs/anvio-master/anvio/anvio/genomedescriptions.py", line 95, in list_HMM_info_and_quit
    s = list(self.genomes.values())[0]['hmm_sources_info'][source]
KeyError: 'hmm_sources_info'
```

**Comment by meren** [comment] 2018-04-27 21:59
Duplicate of #816

**Closed** 2018-04-27 22:50 UTC
Labels: bug, contigs database, phylogenomic workflow
